[general]
root_path = /workspaces/CodexOpenExtraData/data/2026-01-28
file_name = 2026-01-28-09-31-37
;root_path = /workspaces/CodexOpenExtraData/data/2026-04-16
;file_name = 2026-04-16-17-13-20
; root_path = /workspaces/CodexOpenExtraData/data/2025-04-17
; file_name = 2025-04-17-15-03-27-car+bycicle
start_time = 0
end_time = 0
current_time = 0
pause_time = 0.1
b_compensation_cloud = 0
b_lt_none_rt = 1
b_bin_or_pcd = 1
; b_jpg_or_png = 0
b_jpg_or_png = 0
b_txt_or_pcd = 0
b_imu_vec = 0
b_pose_vec = 0

[topics]
b_do_undistort = 0

[calibration]
calib_file_dir = /workspaces/CodexOpen/install/common/GreenMengShi193/calib
;calib_file_dir = /workspaces/CodexOpen/install/common/iRobot193/calib

[device_names]
LidarType = rs128
; LidarType = m1p
;LidarType = mid360
CameraName = ar0231_front,ar0231_left_front,ar0231_right_front
;CameraName = s11a60_front,s11a60_front_left,s11a60_front_right
;CameraName = s11a60_front_left,s11a60_front,s11a60_front_right
InfraName = p12_front,p12_left_front,p12_right_front
StarName = ar0231_front_120
RadarType = ars408
Radar4DType = ars548
; Radar4DType = hugin_arbe
