[general]
root_path = /media/jojo/WorkStation/test/2025-01-09
; 注意路径不能有中文
file_name = 2025-01-09-09-15-36
start_time = 0
; 0 ==> 默认第一帧作为开始
end_time = 0
current_time = 0
pause_time = 0.1
; for step use frame by frame
b_compensation_cloud = 0
b_lt_none_rt = 1
; 0 1 2 => left 90 none right 90
b_bin_or_pcd = 0
; for lidar
b_undistort = 0
b_jpg_or_png = 0
; 0 1 =>  jpg, png
b_txt_or_pcd = 0
; for radar 4d

[topics]
b_do_undistort = 0

[calibration]
calib_file_dir = /media/jojo/AQiDePan/CodexOpen/install/common/GreenMengShi193/calib

[device_names]
LidarType = m1p
CameraName = ar0231_front,ar0231_left,ar0231_right
InfraName = p12_front
StarName = ar0231_front_120
RadarType = ars408
Radar4DType = ars548
#Radar4DType = hugin_arbe

