// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/common_msgs/routing_msgs/poi.proto

#include "modules/common_msgs/routing_msgs/poi.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fgeometry_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fgeometry_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PointENU;
}  // namespace protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fgeometry_2eproto
namespace protobuf_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5fgeometry_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5fgeometry_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Polygon;
}  // namespace protobuf_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5fgeometry_2eproto
namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_LaneWaypoint;
}  // namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto
namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_Landmark;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_ParkingInfo;
}  // namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto
namespace apollo {
namespace routing {
class ParkingInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ParkingInfo>
      _instance;
} _ParkingInfo_default_instance_;
class LandmarkDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Landmark>
      _instance;
} _Landmark_default_instance_;
class POIDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<POI>
      _instance;
} _POI_default_instance_;
}  // namespace routing
}  // namespace apollo
namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto {
static void InitDefaultsParkingInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::routing::_ParkingInfo_default_instance_;
    new (ptr) ::apollo::routing::ParkingInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::routing::ParkingInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_ParkingInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsParkingInfo}, {
      &protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fgeometry_2eproto::scc_info_PointENU.base,
      &protobuf_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5fgeometry_2eproto::scc_info_Polygon.base,}};

static void InitDefaultsLandmark() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::routing::_Landmark_default_instance_;
    new (ptr) ::apollo::routing::Landmark();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::routing::Landmark::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_Landmark =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsLandmark}, {
      &protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto::scc_info_LaneWaypoint.base,
      &protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::scc_info_ParkingInfo.base,}};

static void InitDefaultsPOI() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::routing::_POI_default_instance_;
    new (ptr) ::apollo::routing::POI();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::routing::POI::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_POI =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPOI}, {
      &protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::scc_info_Landmark.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ParkingInfo.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Landmark.base);
  ::google::protobuf::internal::InitSCC(&scc_info_POI.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::ParkingInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::ParkingInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::ParkingInfo, parking_space_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::ParkingInfo, parking_point_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::ParkingInfo, parking_space_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::ParkingInfo, corner_point_),
  0,
  1,
  3,
  2,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::Landmark, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::Landmark, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::Landmark, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::Landmark, waypoint_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::Landmark, parking_space_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::Landmark, parking_info_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::Landmark, cycle_number_),
  0,
  ~0u,
  1,
  2,
  3,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::POI, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::POI, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::routing::POI, landmark_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::apollo::routing::ParkingInfo)},
  { 13, 23, sizeof(::apollo::routing::Landmark)},
  { 28, 34, sizeof(::apollo::routing::POI)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::routing::_ParkingInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::routing::_Landmark_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::routing::_POI_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "modules/common_msgs/routing_msgs/poi.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n*modules/common_msgs/routing_msgs/poi.p"
      "roto\022\016apollo.routing\032/modules/common_msg"
      "s/map_msgs/map_geometry.proto\032-modules/c"
      "ommon_msgs/basic_msgs/geometry.proto\032/mo"
      "dules/common_msgs/routing_msgs/geometry."
      "proto\"\302\001\n\013ParkingInfo\022\030\n\020parking_space_i"
      "d\030\001 \001(\t\022.\n\rparking_point\030\002 \001(\0132\027.apollo."
      "common.PointENU\022<\n\022parking_space_type\030\003 "
      "\001(\0162 .apollo.routing.ParkingSpaceType\022+\n"
      "\014corner_point\030\004 \001(\0132\025.apollo.hdmap.Polyg"
      "on\"\257\001\n\010Landmark\022\014\n\004name\030\001 \001(\t\022.\n\010waypoin"
      "t\030\002 \003(\0132\034.apollo.routing.LaneWaypoint\022\034\n"
      "\020parking_space_id\030\003 \001(\tB\002\030\001\0221\n\014parking_i"
      "nfo\030\004 \001(\0132\033.apollo.routing.ParkingInfo\022\024"
      "\n\014cycle_number\030\005 \001(\005\"1\n\003POI\022*\n\010landmark\030"
      "\001 \003(\0132\030.apollo.routing.Landmark*;\n\020Parki"
      "ngSpaceType\022\021\n\rVERTICAL_PLOT\020\000\022\024\n\020PARALL"
      "EL_PARKING\020\001"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 692);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "modules/common_msgs/routing_msgs/poi.proto", &protobuf_RegisterTypes);
  ::protobuf_modules_2fcommon_5fmsgs_2fmap_5fmsgs_2fmap_5fgeometry_2eproto::AddDescriptors();
  ::protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fgeometry_2eproto::AddDescriptors();
  ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fgeometry_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto
namespace apollo {
namespace routing {
const ::google::protobuf::EnumDescriptor* ParkingSpaceType_descriptor() {
  protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::file_level_enum_descriptors[0];
}
bool ParkingSpaceType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ParkingInfo::InitAsDefaultInstance() {
  ::apollo::routing::_ParkingInfo_default_instance_._instance.get_mutable()->parking_point_ = const_cast< ::apollo::common::PointENU*>(
      ::apollo::common::PointENU::internal_default_instance());
  ::apollo::routing::_ParkingInfo_default_instance_._instance.get_mutable()->corner_point_ = const_cast< ::apollo::hdmap::Polygon*>(
      ::apollo::hdmap::Polygon::internal_default_instance());
}
void ParkingInfo::clear_parking_point() {
  if (parking_point_ != NULL) parking_point_->Clear();
  clear_has_parking_point();
}
void ParkingInfo::clear_corner_point() {
  if (corner_point_ != NULL) corner_point_->Clear();
  clear_has_corner_point();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParkingInfo::kParkingSpaceIdFieldNumber;
const int ParkingInfo::kParkingPointFieldNumber;
const int ParkingInfo::kParkingSpaceTypeFieldNumber;
const int ParkingInfo::kCornerPointFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParkingInfo::ParkingInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::scc_info_ParkingInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.routing.ParkingInfo)
}
ParkingInfo::ParkingInfo(const ParkingInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  parking_space_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_parking_space_id()) {
    parking_space_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parking_space_id_);
  }
  if (from.has_parking_point()) {
    parking_point_ = new ::apollo::common::PointENU(*from.parking_point_);
  } else {
    parking_point_ = NULL;
  }
  if (from.has_corner_point()) {
    corner_point_ = new ::apollo::hdmap::Polygon(*from.corner_point_);
  } else {
    corner_point_ = NULL;
  }
  parking_space_type_ = from.parking_space_type_;
  // @@protoc_insertion_point(copy_constructor:apollo.routing.ParkingInfo)
}

void ParkingInfo::SharedCtor() {
  parking_space_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&parking_point_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&parking_space_type_) -
      reinterpret_cast<char*>(&parking_point_)) + sizeof(parking_space_type_));
}

ParkingInfo::~ParkingInfo() {
  // @@protoc_insertion_point(destructor:apollo.routing.ParkingInfo)
  SharedDtor();
}

void ParkingInfo::SharedDtor() {
  parking_space_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete parking_point_;
  if (this != internal_default_instance()) delete corner_point_;
}

void ParkingInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ParkingInfo::descriptor() {
  ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ParkingInfo& ParkingInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::scc_info_ParkingInfo.base);
  return *internal_default_instance();
}


void ParkingInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.routing.ParkingInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      parking_space_id_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(parking_point_ != NULL);
      parking_point_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(corner_point_ != NULL);
      corner_point_->Clear();
    }
  }
  parking_space_type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ParkingInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.routing.ParkingInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string parking_space_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_parking_space_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->parking_space_id().data(), static_cast<int>(this->parking_space_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.routing.ParkingInfo.parking_space_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.common.PointENU parking_point = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_parking_point()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.routing.ParkingSpaceType parking_space_type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::apollo::routing::ParkingSpaceType_IsValid(value)) {
            set_parking_space_type(static_cast< ::apollo::routing::ParkingSpaceType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                3, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.hdmap.Polygon corner_point = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_corner_point()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.routing.ParkingInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.routing.ParkingInfo)
  return false;
#undef DO_
}

void ParkingInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.routing.ParkingInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string parking_space_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parking_space_id().data(), static_cast<int>(this->parking_space_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.routing.ParkingInfo.parking_space_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->parking_space_id(), output);
  }

  // optional .apollo.common.PointENU parking_point = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_parking_point(), output);
  }

  // optional .apollo.routing.ParkingSpaceType parking_space_type = 3;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->parking_space_type(), output);
  }

  // optional .apollo.hdmap.Polygon corner_point = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_corner_point(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.routing.ParkingInfo)
}

::google::protobuf::uint8* ParkingInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.routing.ParkingInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string parking_space_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parking_space_id().data(), static_cast<int>(this->parking_space_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.routing.ParkingInfo.parking_space_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->parking_space_id(), target);
  }

  // optional .apollo.common.PointENU parking_point = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_parking_point(), deterministic, target);
  }

  // optional .apollo.routing.ParkingSpaceType parking_space_type = 3;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->parking_space_type(), target);
  }

  // optional .apollo.hdmap.Polygon corner_point = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_corner_point(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.routing.ParkingInfo)
  return target;
}

size_t ParkingInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.routing.ParkingInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 15u) {
    // optional string parking_space_id = 1;
    if (has_parking_space_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->parking_space_id());
    }

    // optional .apollo.common.PointENU parking_point = 2;
    if (has_parking_point()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *parking_point_);
    }

    // optional .apollo.hdmap.Polygon corner_point = 4;
    if (has_corner_point()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *corner_point_);
    }

    // optional .apollo.routing.ParkingSpaceType parking_space_type = 3;
    if (has_parking_space_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->parking_space_type());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ParkingInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.routing.ParkingInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ParkingInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ParkingInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.routing.ParkingInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.routing.ParkingInfo)
    MergeFrom(*source);
  }
}

void ParkingInfo::MergeFrom(const ParkingInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.routing.ParkingInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_parking_space_id();
      parking_space_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parking_space_id_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_parking_point()->::apollo::common::PointENU::MergeFrom(from.parking_point());
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_corner_point()->::apollo::hdmap::Polygon::MergeFrom(from.corner_point());
    }
    if (cached_has_bits & 0x00000008u) {
      parking_space_type_ = from.parking_space_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ParkingInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.routing.ParkingInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParkingInfo::CopyFrom(const ParkingInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.routing.ParkingInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParkingInfo::IsInitialized() const {
  return true;
}

void ParkingInfo::Swap(ParkingInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParkingInfo::InternalSwap(ParkingInfo* other) {
  using std::swap;
  parking_space_id_.Swap(&other->parking_space_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(parking_point_, other->parking_point_);
  swap(corner_point_, other->corner_point_);
  swap(parking_space_type_, other->parking_space_type_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ParkingInfo::GetMetadata() const {
  protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Landmark::InitAsDefaultInstance() {
  ::apollo::routing::_Landmark_default_instance_._instance.get_mutable()->parking_info_ = const_cast< ::apollo::routing::ParkingInfo*>(
      ::apollo::routing::ParkingInfo::internal_default_instance());
}
void Landmark::clear_waypoint() {
  waypoint_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Landmark::kNameFieldNumber;
const int Landmark::kWaypointFieldNumber;
const int Landmark::kParkingSpaceIdFieldNumber;
const int Landmark::kParkingInfoFieldNumber;
const int Landmark::kCycleNumberFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Landmark::Landmark()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::scc_info_Landmark.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.routing.Landmark)
}
Landmark::Landmark(const Landmark& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      waypoint_(from.waypoint_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  parking_space_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_parking_space_id()) {
    parking_space_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parking_space_id_);
  }
  if (from.has_parking_info()) {
    parking_info_ = new ::apollo::routing::ParkingInfo(*from.parking_info_);
  } else {
    parking_info_ = NULL;
  }
  cycle_number_ = from.cycle_number_;
  // @@protoc_insertion_point(copy_constructor:apollo.routing.Landmark)
}

void Landmark::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  parking_space_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&parking_info_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cycle_number_) -
      reinterpret_cast<char*>(&parking_info_)) + sizeof(cycle_number_));
}

Landmark::~Landmark() {
  // @@protoc_insertion_point(destructor:apollo.routing.Landmark)
  SharedDtor();
}

void Landmark::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  parking_space_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete parking_info_;
}

void Landmark::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Landmark::descriptor() {
  ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Landmark& Landmark::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::scc_info_Landmark.base);
  return *internal_default_instance();
}


void Landmark::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.routing.Landmark)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  waypoint_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      parking_space_id_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(parking_info_ != NULL);
      parking_info_->Clear();
    }
  }
  cycle_number_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Landmark::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.routing.Landmark)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.routing.Landmark.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .apollo.routing.LaneWaypoint waypoint = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_waypoint()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string parking_space_id = 3 [deprecated = true];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_parking_space_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->parking_space_id().data(), static_cast<int>(this->parking_space_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.routing.Landmark.parking_space_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.routing.ParkingInfo parking_info = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_parking_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 cycle_number = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          set_has_cycle_number();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cycle_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.routing.Landmark)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.routing.Landmark)
  return false;
#undef DO_
}

void Landmark::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.routing.Landmark)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.routing.Landmark.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .apollo.routing.LaneWaypoint waypoint = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->waypoint_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->waypoint(static_cast<int>(i)),
      output);
  }

  // optional string parking_space_id = 3 [deprecated = true];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parking_space_id().data(), static_cast<int>(this->parking_space_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.routing.Landmark.parking_space_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->parking_space_id(), output);
  }

  // optional .apollo.routing.ParkingInfo parking_info = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_parking_info(), output);
  }

  // optional int32 cycle_number = 5;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->cycle_number(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.routing.Landmark)
}

::google::protobuf::uint8* Landmark::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.routing.Landmark)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.routing.Landmark.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .apollo.routing.LaneWaypoint waypoint = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->waypoint_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->waypoint(static_cast<int>(i)), deterministic, target);
  }

  // optional string parking_space_id = 3 [deprecated = true];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parking_space_id().data(), static_cast<int>(this->parking_space_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.routing.Landmark.parking_space_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->parking_space_id(), target);
  }

  // optional .apollo.routing.ParkingInfo parking_info = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_parking_info(), deterministic, target);
  }

  // optional int32 cycle_number = 5;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->cycle_number(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.routing.Landmark)
  return target;
}

size_t Landmark::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.routing.Landmark)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .apollo.routing.LaneWaypoint waypoint = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->waypoint_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->waypoint(static_cast<int>(i)));
    }
  }

  if (_has_bits_[0 / 32] & 15u) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional string parking_space_id = 3 [deprecated = true];
    if (has_parking_space_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->parking_space_id());
    }

    // optional .apollo.routing.ParkingInfo parking_info = 4;
    if (has_parking_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *parking_info_);
    }

    // optional int32 cycle_number = 5;
    if (has_cycle_number()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cycle_number());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Landmark::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.routing.Landmark)
  GOOGLE_DCHECK_NE(&from, this);
  const Landmark* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Landmark>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.routing.Landmark)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.routing.Landmark)
    MergeFrom(*source);
  }
}

void Landmark::MergeFrom(const Landmark& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.routing.Landmark)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  waypoint_.MergeFrom(from.waypoint_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_parking_space_id();
      parking_space_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parking_space_id_);
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_parking_info()->::apollo::routing::ParkingInfo::MergeFrom(from.parking_info());
    }
    if (cached_has_bits & 0x00000008u) {
      cycle_number_ = from.cycle_number_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Landmark::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.routing.Landmark)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Landmark::CopyFrom(const Landmark& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.routing.Landmark)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Landmark::IsInitialized() const {
  return true;
}

void Landmark::Swap(Landmark* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Landmark::InternalSwap(Landmark* other) {
  using std::swap;
  CastToBase(&waypoint_)->InternalSwap(CastToBase(&other->waypoint_));
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  parking_space_id_.Swap(&other->parking_space_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(parking_info_, other->parking_info_);
  swap(cycle_number_, other->cycle_number_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Landmark::GetMetadata() const {
  protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void POI::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int POI::kLandmarkFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

POI::POI()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::scc_info_POI.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.routing.POI)
}
POI::POI(const POI& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      landmark_(from.landmark_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:apollo.routing.POI)
}

void POI::SharedCtor() {
}

POI::~POI() {
  // @@protoc_insertion_point(destructor:apollo.routing.POI)
  SharedDtor();
}

void POI::SharedDtor() {
}

void POI::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* POI::descriptor() {
  ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const POI& POI::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::scc_info_POI.base);
  return *internal_default_instance();
}


void POI::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.routing.POI)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  landmark_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool POI::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.routing.POI)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .apollo.routing.Landmark landmark = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_landmark()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.routing.POI)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.routing.POI)
  return false;
#undef DO_
}

void POI::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.routing.POI)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.routing.Landmark landmark = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->landmark_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->landmark(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.routing.POI)
}

::google::protobuf::uint8* POI::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.routing.POI)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .apollo.routing.Landmark landmark = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->landmark_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->landmark(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.routing.POI)
  return target;
}

size_t POI::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.routing.POI)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .apollo.routing.Landmark landmark = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->landmark_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->landmark(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void POI::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.routing.POI)
  GOOGLE_DCHECK_NE(&from, this);
  const POI* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const POI>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.routing.POI)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.routing.POI)
    MergeFrom(*source);
  }
}

void POI::MergeFrom(const POI& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.routing.POI)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  landmark_.MergeFrom(from.landmark_);
}

void POI::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.routing.POI)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void POI::CopyFrom(const POI& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.routing.POI)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool POI::IsInitialized() const {
  return true;
}

void POI::Swap(POI* other) {
  if (other == this) return;
  InternalSwap(other);
}
void POI::InternalSwap(POI* other) {
  using std::swap;
  CastToBase(&landmark_)->InternalSwap(CastToBase(&other->landmark_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata POI::GetMetadata() const {
  protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2fpoi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace routing
}  // namespace apollo
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::routing::ParkingInfo* Arena::CreateMaybeMessage< ::apollo::routing::ParkingInfo >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::routing::ParkingInfo >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::routing::Landmark* Arena::CreateMaybeMessage< ::apollo::routing::Landmark >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::routing::Landmark >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::routing::POI* Arena::CreateMaybeMessage< ::apollo::routing::POI >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::routing::POI >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
