// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/common_msgs/monitor_msgs/system_status.proto

#ifndef PROTOBUF_INCLUDED_modules_2fcommon_5fmsgs_2fmonitor_5fmsgs_2fsystem_5fstatus_2eproto
#define PROTOBUF_INCLUDED_modules_2fcommon_5fmsgs_2fmonitor_5fmsgs_2fsystem_5fstatus_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "modules/common_msgs/basic_msgs/header.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2fmonitor_5fmsgs_2fsystem_5fstatus_2eproto 

namespace protobuf_modules_2fcommon_5fmsgs_2fmonitor_5fmsgs_2fsystem_5fstatus_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_modules_2fcommon_5fmsgs_2fmonitor_5fmsgs_2fsystem_5fstatus_2eproto
namespace apollo {
namespace monitor {
class Component;
class ComponentDefaultTypeInternal;
extern ComponentDefaultTypeInternal _Component_default_instance_;
class ComponentStatus;
class ComponentStatusDefaultTypeInternal;
extern ComponentStatusDefaultTypeInternal _ComponentStatus_default_instance_;
class SystemStatus;
class SystemStatusDefaultTypeInternal;
extern SystemStatusDefaultTypeInternal _SystemStatus_default_instance_;
class SystemStatus_ComponentsEntry_DoNotUse;
class SystemStatus_ComponentsEntry_DoNotUseDefaultTypeInternal;
extern SystemStatus_ComponentsEntry_DoNotUseDefaultTypeInternal _SystemStatus_ComponentsEntry_DoNotUse_default_instance_;
class SystemStatus_GlobalComponentsEntry_DoNotUse;
class SystemStatus_GlobalComponentsEntry_DoNotUseDefaultTypeInternal;
extern SystemStatus_GlobalComponentsEntry_DoNotUseDefaultTypeInternal _SystemStatus_GlobalComponentsEntry_DoNotUse_default_instance_;
class SystemStatus_HmiModulesEntry_DoNotUse;
class SystemStatus_HmiModulesEntry_DoNotUseDefaultTypeInternal;
extern SystemStatus_HmiModulesEntry_DoNotUseDefaultTypeInternal _SystemStatus_HmiModulesEntry_DoNotUse_default_instance_;
class SystemStatus_OtherComponentsEntry_DoNotUse;
class SystemStatus_OtherComponentsEntry_DoNotUseDefaultTypeInternal;
extern SystemStatus_OtherComponentsEntry_DoNotUseDefaultTypeInternal _SystemStatus_OtherComponentsEntry_DoNotUse_default_instance_;
}  // namespace monitor
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::monitor::Component* Arena::CreateMaybeMessage<::apollo::monitor::Component>(Arena*);
template<> ::apollo::monitor::ComponentStatus* Arena::CreateMaybeMessage<::apollo::monitor::ComponentStatus>(Arena*);
template<> ::apollo::monitor::SystemStatus* Arena::CreateMaybeMessage<::apollo::monitor::SystemStatus>(Arena*);
template<> ::apollo::monitor::SystemStatus_ComponentsEntry_DoNotUse* Arena::CreateMaybeMessage<::apollo::monitor::SystemStatus_ComponentsEntry_DoNotUse>(Arena*);
template<> ::apollo::monitor::SystemStatus_GlobalComponentsEntry_DoNotUse* Arena::CreateMaybeMessage<::apollo::monitor::SystemStatus_GlobalComponentsEntry_DoNotUse>(Arena*);
template<> ::apollo::monitor::SystemStatus_HmiModulesEntry_DoNotUse* Arena::CreateMaybeMessage<::apollo::monitor::SystemStatus_HmiModulesEntry_DoNotUse>(Arena*);
template<> ::apollo::monitor::SystemStatus_OtherComponentsEntry_DoNotUse* Arena::CreateMaybeMessage<::apollo::monitor::SystemStatus_OtherComponentsEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace monitor {

enum ComponentStatus_Status {
  ComponentStatus_Status_UNKNOWN = 0,
  ComponentStatus_Status_OK = 1,
  ComponentStatus_Status_WARN = 2,
  ComponentStatus_Status_ERROR = 3,
  ComponentStatus_Status_FATAL = 4
};
bool ComponentStatus_Status_IsValid(int value);
const ComponentStatus_Status ComponentStatus_Status_Status_MIN = ComponentStatus_Status_UNKNOWN;
const ComponentStatus_Status ComponentStatus_Status_Status_MAX = ComponentStatus_Status_FATAL;
const int ComponentStatus_Status_Status_ARRAYSIZE = ComponentStatus_Status_Status_MAX + 1;

const ::google::protobuf::EnumDescriptor* ComponentStatus_Status_descriptor();
inline const ::std::string& ComponentStatus_Status_Name(ComponentStatus_Status value) {
  return ::google::protobuf::internal::NameOfEnum(
    ComponentStatus_Status_descriptor(), value);
}
inline bool ComponentStatus_Status_Parse(
    const ::std::string& name, ComponentStatus_Status* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ComponentStatus_Status>(
    ComponentStatus_Status_descriptor(), name, value);
}
// ===================================================================

class ComponentStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.monitor.ComponentStatus) */ {
 public:
  ComponentStatus();
  virtual ~ComponentStatus();

  ComponentStatus(const ComponentStatus& from);

  inline ComponentStatus& operator=(const ComponentStatus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ComponentStatus(ComponentStatus&& from) noexcept
    : ComponentStatus() {
    *this = ::std::move(from);
  }

  inline ComponentStatus& operator=(ComponentStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ComponentStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ComponentStatus* internal_default_instance() {
    return reinterpret_cast<const ComponentStatus*>(
               &_ComponentStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ComponentStatus* other);
  friend void swap(ComponentStatus& a, ComponentStatus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ComponentStatus* New() const final {
    return CreateMaybeMessage<ComponentStatus>(NULL);
  }

  ComponentStatus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ComponentStatus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ComponentStatus& from);
  void MergeFrom(const ComponentStatus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ComponentStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ComponentStatus_Status Status;
  static const Status UNKNOWN =
    ComponentStatus_Status_UNKNOWN;
  static const Status OK =
    ComponentStatus_Status_OK;
  static const Status WARN =
    ComponentStatus_Status_WARN;
  static const Status ERROR =
    ComponentStatus_Status_ERROR;
  static const Status FATAL =
    ComponentStatus_Status_FATAL;
  static inline bool Status_IsValid(int value) {
    return ComponentStatus_Status_IsValid(value);
  }
  static const Status Status_MIN =
    ComponentStatus_Status_Status_MIN;
  static const Status Status_MAX =
    ComponentStatus_Status_Status_MAX;
  static const int Status_ARRAYSIZE =
    ComponentStatus_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Status_descriptor() {
    return ComponentStatus_Status_descriptor();
  }
  static inline const ::std::string& Status_Name(Status value) {
    return ComponentStatus_Status_Name(value);
  }
  static inline bool Status_Parse(const ::std::string& name,
      Status* value) {
    return ComponentStatus_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string message = 2;
  bool has_message() const;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // optional .apollo.monitor.ComponentStatus.Status status = 1 [default = UNKNOWN];
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::apollo::monitor::ComponentStatus_Status status() const;
  void set_status(::apollo::monitor::ComponentStatus_Status value);

  // @@protoc_insertion_point(class_scope:apollo.monitor.ComponentStatus)
 private:
  void set_has_status();
  void clear_has_status();
  void set_has_message();
  void clear_has_message();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  int status_;
  friend struct ::protobuf_modules_2fcommon_5fmsgs_2fmonitor_5fmsgs_2fsystem_5fstatus_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Component : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.monitor.Component) */ {
 public:
  Component();
  virtual ~Component();

  Component(const Component& from);

  inline Component& operator=(const Component& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Component(Component&& from) noexcept
    : Component() {
    *this = ::std::move(from);
  }

  inline Component& operator=(Component&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Component& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Component* internal_default_instance() {
    return reinterpret_cast<const Component*>(
               &_Component_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Component* other);
  friend void swap(Component& a, Component& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Component* New() const final {
    return CreateMaybeMessage<Component>(NULL);
  }

  Component* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Component>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Component& from);
  void MergeFrom(const Component& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Component* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.monitor.ComponentStatus summary = 1;
  bool has_summary() const;
  void clear_summary();
  static const int kSummaryFieldNumber = 1;
  private:
  const ::apollo::monitor::ComponentStatus& _internal_summary() const;
  public:
  const ::apollo::monitor::ComponentStatus& summary() const;
  ::apollo::monitor::ComponentStatus* release_summary();
  ::apollo::monitor::ComponentStatus* mutable_summary();
  void set_allocated_summary(::apollo::monitor::ComponentStatus* summary);

  // optional .apollo.monitor.ComponentStatus process_status = 2;
  bool has_process_status() const;
  void clear_process_status();
  static const int kProcessStatusFieldNumber = 2;
  private:
  const ::apollo::monitor::ComponentStatus& _internal_process_status() const;
  public:
  const ::apollo::monitor::ComponentStatus& process_status() const;
  ::apollo::monitor::ComponentStatus* release_process_status();
  ::apollo::monitor::ComponentStatus* mutable_process_status();
  void set_allocated_process_status(::apollo::monitor::ComponentStatus* process_status);

  // optional .apollo.monitor.ComponentStatus channel_status = 3;
  bool has_channel_status() const;
  void clear_channel_status();
  static const int kChannelStatusFieldNumber = 3;
  private:
  const ::apollo::monitor::ComponentStatus& _internal_channel_status() const;
  public:
  const ::apollo::monitor::ComponentStatus& channel_status() const;
  ::apollo::monitor::ComponentStatus* release_channel_status();
  ::apollo::monitor::ComponentStatus* mutable_channel_status();
  void set_allocated_channel_status(::apollo::monitor::ComponentStatus* channel_status);

  // optional .apollo.monitor.ComponentStatus resource_status = 4;
  bool has_resource_status() const;
  void clear_resource_status();
  static const int kResourceStatusFieldNumber = 4;
  private:
  const ::apollo::monitor::ComponentStatus& _internal_resource_status() const;
  public:
  const ::apollo::monitor::ComponentStatus& resource_status() const;
  ::apollo::monitor::ComponentStatus* release_resource_status();
  ::apollo::monitor::ComponentStatus* mutable_resource_status();
  void set_allocated_resource_status(::apollo::monitor::ComponentStatus* resource_status);

  // optional .apollo.monitor.ComponentStatus other_status = 5;
  bool has_other_status() const;
  void clear_other_status();
  static const int kOtherStatusFieldNumber = 5;
  private:
  const ::apollo::monitor::ComponentStatus& _internal_other_status() const;
  public:
  const ::apollo::monitor::ComponentStatus& other_status() const;
  ::apollo::monitor::ComponentStatus* release_other_status();
  ::apollo::monitor::ComponentStatus* mutable_other_status();
  void set_allocated_other_status(::apollo::monitor::ComponentStatus* other_status);

  // optional .apollo.monitor.ComponentStatus module_status = 6;
  bool has_module_status() const;
  void clear_module_status();
  static const int kModuleStatusFieldNumber = 6;
  private:
  const ::apollo::monitor::ComponentStatus& _internal_module_status() const;
  public:
  const ::apollo::monitor::ComponentStatus& module_status() const;
  ::apollo::monitor::ComponentStatus* release_module_status();
  ::apollo::monitor::ComponentStatus* mutable_module_status();
  void set_allocated_module_status(::apollo::monitor::ComponentStatus* module_status);

  // @@protoc_insertion_point(class_scope:apollo.monitor.Component)
 private:
  void set_has_summary();
  void clear_has_summary();
  void set_has_process_status();
  void clear_has_process_status();
  void set_has_channel_status();
  void clear_has_channel_status();
  void set_has_resource_status();
  void clear_has_resource_status();
  void set_has_other_status();
  void clear_has_other_status();
  void set_has_module_status();
  void clear_has_module_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::apollo::monitor::ComponentStatus* summary_;
  ::apollo::monitor::ComponentStatus* process_status_;
  ::apollo::monitor::ComponentStatus* channel_status_;
  ::apollo::monitor::ComponentStatus* resource_status_;
  ::apollo::monitor::ComponentStatus* other_status_;
  ::apollo::monitor::ComponentStatus* module_status_;
  friend struct ::protobuf_modules_2fcommon_5fmsgs_2fmonitor_5fmsgs_2fsystem_5fstatus_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SystemStatus_HmiModulesEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<SystemStatus_HmiModulesEntry_DoNotUse, 
    ::std::string, ::apollo::monitor::ComponentStatus,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<SystemStatus_HmiModulesEntry_DoNotUse, 
    ::std::string, ::apollo::monitor::ComponentStatus,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  SystemStatus_HmiModulesEntry_DoNotUse();
  SystemStatus_HmiModulesEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const SystemStatus_HmiModulesEntry_DoNotUse& other);
  static const SystemStatus_HmiModulesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SystemStatus_HmiModulesEntry_DoNotUse*>(&_SystemStatus_HmiModulesEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class SystemStatus_ComponentsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<SystemStatus_ComponentsEntry_DoNotUse, 
    ::std::string, ::apollo::monitor::Component,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<SystemStatus_ComponentsEntry_DoNotUse, 
    ::std::string, ::apollo::monitor::Component,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  SystemStatus_ComponentsEntry_DoNotUse();
  SystemStatus_ComponentsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const SystemStatus_ComponentsEntry_DoNotUse& other);
  static const SystemStatus_ComponentsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SystemStatus_ComponentsEntry_DoNotUse*>(&_SystemStatus_ComponentsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class SystemStatus_OtherComponentsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<SystemStatus_OtherComponentsEntry_DoNotUse, 
    ::std::string, ::apollo::monitor::ComponentStatus,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<SystemStatus_OtherComponentsEntry_DoNotUse, 
    ::std::string, ::apollo::monitor::ComponentStatus,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  SystemStatus_OtherComponentsEntry_DoNotUse();
  SystemStatus_OtherComponentsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const SystemStatus_OtherComponentsEntry_DoNotUse& other);
  static const SystemStatus_OtherComponentsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SystemStatus_OtherComponentsEntry_DoNotUse*>(&_SystemStatus_OtherComponentsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class SystemStatus_GlobalComponentsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<SystemStatus_GlobalComponentsEntry_DoNotUse, 
    ::std::string, ::apollo::monitor::Component,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<SystemStatus_GlobalComponentsEntry_DoNotUse, 
    ::std::string, ::apollo::monitor::Component,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  SystemStatus_GlobalComponentsEntry_DoNotUse();
  SystemStatus_GlobalComponentsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const SystemStatus_GlobalComponentsEntry_DoNotUse& other);
  static const SystemStatus_GlobalComponentsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SystemStatus_GlobalComponentsEntry_DoNotUse*>(&_SystemStatus_GlobalComponentsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class SystemStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.monitor.SystemStatus) */ {
 public:
  SystemStatus();
  virtual ~SystemStatus();

  SystemStatus(const SystemStatus& from);

  inline SystemStatus& operator=(const SystemStatus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SystemStatus(SystemStatus&& from) noexcept
    : SystemStatus() {
    *this = ::std::move(from);
  }

  inline SystemStatus& operator=(SystemStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SystemStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SystemStatus* internal_default_instance() {
    return reinterpret_cast<const SystemStatus*>(
               &_SystemStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(SystemStatus* other);
  friend void swap(SystemStatus& a, SystemStatus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SystemStatus* New() const final {
    return CreateMaybeMessage<SystemStatus>(NULL);
  }

  SystemStatus* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SystemStatus>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SystemStatus& from);
  void MergeFrom(const SystemStatus& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SystemStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .apollo.monitor.ComponentStatus> hmi_modules = 7;
  int hmi_modules_size() const;
  void clear_hmi_modules();
  static const int kHmiModulesFieldNumber = 7;
  const ::google::protobuf::Map< ::std::string, ::apollo::monitor::ComponentStatus >&
      hmi_modules() const;
  ::google::protobuf::Map< ::std::string, ::apollo::monitor::ComponentStatus >*
      mutable_hmi_modules();

  // map<string, .apollo.monitor.Component> components = 8;
  int components_size() const;
  void clear_components();
  static const int kComponentsFieldNumber = 8;
  const ::google::protobuf::Map< ::std::string, ::apollo::monitor::Component >&
      components() const;
  ::google::protobuf::Map< ::std::string, ::apollo::monitor::Component >*
      mutable_components();

  // map<string, .apollo.monitor.ComponentStatus> other_components = 10;
  int other_components_size() const;
  void clear_other_components();
  static const int kOtherComponentsFieldNumber = 10;
  const ::google::protobuf::Map< ::std::string, ::apollo::monitor::ComponentStatus >&
      other_components() const;
  ::google::protobuf::Map< ::std::string, ::apollo::monitor::ComponentStatus >*
      mutable_other_components();

  // map<string, .apollo.monitor.Component> global_components = 11;
  int global_components_size() const;
  void clear_global_components();
  static const int kGlobalComponentsFieldNumber = 11;
  const ::google::protobuf::Map< ::std::string, ::apollo::monitor::Component >&
      global_components() const;
  ::google::protobuf::Map< ::std::string, ::apollo::monitor::Component >*
      mutable_global_components();

  // optional string passenger_msg = 4;
  bool has_passenger_msg() const;
  void clear_passenger_msg();
  static const int kPassengerMsgFieldNumber = 4;
  const ::std::string& passenger_msg() const;
  void set_passenger_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_passenger_msg(::std::string&& value);
  #endif
  void set_passenger_msg(const char* value);
  void set_passenger_msg(const char* value, size_t size);
  ::std::string* mutable_passenger_msg();
  ::std::string* release_passenger_msg();
  void set_allocated_passenger_msg(::std::string* passenger_msg);

  // optional .apollo.common.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  const ::apollo::common::Header& _internal_header() const;
  public:
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* release_header();
  ::apollo::common::Header* mutable_header();
  void set_allocated_header(::apollo::common::Header* header);

  // optional double safety_mode_trigger_time = 5;
  bool has_safety_mode_trigger_time() const;
  void clear_safety_mode_trigger_time();
  static const int kSafetyModeTriggerTimeFieldNumber = 5;
  double safety_mode_trigger_time() const;
  void set_safety_mode_trigger_time(double value);

  // optional bool require_emergency_stop = 6;
  bool has_require_emergency_stop() const;
  void clear_require_emergency_stop();
  static const int kRequireEmergencyStopFieldNumber = 6;
  bool require_emergency_stop() const;
  void set_require_emergency_stop(bool value);

  // optional bool is_realtime_in_simulation = 9;
  bool has_is_realtime_in_simulation() const;
  void clear_is_realtime_in_simulation();
  static const int kIsRealtimeInSimulationFieldNumber = 9;
  bool is_realtime_in_simulation() const;
  void set_is_realtime_in_simulation(bool value);

  // optional bool detect_immediately = 12 [default = false];
  bool has_detect_immediately() const;
  void clear_detect_immediately();
  static const int kDetectImmediatelyFieldNumber = 12;
  bool detect_immediately() const;
  void set_detect_immediately(bool value);

  // @@protoc_insertion_point(class_scope:apollo.monitor.SystemStatus)
 private:
  void set_has_header();
  void clear_has_header();
  void set_has_passenger_msg();
  void clear_has_passenger_msg();
  void set_has_safety_mode_trigger_time();
  void clear_has_safety_mode_trigger_time();
  void set_has_require_emergency_stop();
  void clear_has_require_emergency_stop();
  void set_has_is_realtime_in_simulation();
  void clear_has_is_realtime_in_simulation();
  void set_has_detect_immediately();
  void clear_has_detect_immediately();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::MapField<
      SystemStatus_HmiModulesEntry_DoNotUse,
      ::std::string, ::apollo::monitor::ComponentStatus,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > hmi_modules_;
  ::google::protobuf::internal::MapField<
      SystemStatus_ComponentsEntry_DoNotUse,
      ::std::string, ::apollo::monitor::Component,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > components_;
  ::google::protobuf::internal::MapField<
      SystemStatus_OtherComponentsEntry_DoNotUse,
      ::std::string, ::apollo::monitor::ComponentStatus,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > other_components_;
  ::google::protobuf::internal::MapField<
      SystemStatus_GlobalComponentsEntry_DoNotUse,
      ::std::string, ::apollo::monitor::Component,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > global_components_;
  ::google::protobuf::internal::ArenaStringPtr passenger_msg_;
  ::apollo::common::Header* header_;
  double safety_mode_trigger_time_;
  bool require_emergency_stop_;
  bool is_realtime_in_simulation_;
  bool detect_immediately_;
  friend struct ::protobuf_modules_2fcommon_5fmsgs_2fmonitor_5fmsgs_2fsystem_5fstatus_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ComponentStatus

// optional .apollo.monitor.ComponentStatus.Status status = 1 [default = UNKNOWN];
inline bool ComponentStatus::has_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ComponentStatus::set_has_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ComponentStatus::clear_has_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ComponentStatus::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::apollo::monitor::ComponentStatus_Status ComponentStatus::status() const {
  // @@protoc_insertion_point(field_get:apollo.monitor.ComponentStatus.status)
  return static_cast< ::apollo::monitor::ComponentStatus_Status >(status_);
}
inline void ComponentStatus::set_status(::apollo::monitor::ComponentStatus_Status value) {
  assert(::apollo::monitor::ComponentStatus_Status_IsValid(value));
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:apollo.monitor.ComponentStatus.status)
}

// optional string message = 2;
inline bool ComponentStatus::has_message() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ComponentStatus::set_has_message() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ComponentStatus::clear_has_message() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ComponentStatus::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_message();
}
inline const ::std::string& ComponentStatus::message() const {
  // @@protoc_insertion_point(field_get:apollo.monitor.ComponentStatus.message)
  return message_.GetNoArena();
}
inline void ComponentStatus::set_message(const ::std::string& value) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.monitor.ComponentStatus.message)
}
#if LANG_CXX11
inline void ComponentStatus::set_message(::std::string&& value) {
  set_has_message();
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.monitor.ComponentStatus.message)
}
#endif
inline void ComponentStatus::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.monitor.ComponentStatus.message)
}
inline void ComponentStatus::set_message(const char* value, size_t size) {
  set_has_message();
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.monitor.ComponentStatus.message)
}
inline ::std::string* ComponentStatus::mutable_message() {
  set_has_message();
  // @@protoc_insertion_point(field_mutable:apollo.monitor.ComponentStatus.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ComponentStatus::release_message() {
  // @@protoc_insertion_point(field_release:apollo.monitor.ComponentStatus.message)
  if (!has_message()) {
    return NULL;
  }
  clear_has_message();
  return message_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComponentStatus::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    set_has_message();
  } else {
    clear_has_message();
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:apollo.monitor.ComponentStatus.message)
}

// -------------------------------------------------------------------

// Component

// optional .apollo.monitor.ComponentStatus summary = 1;
inline bool Component::has_summary() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Component::set_has_summary() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Component::clear_has_summary() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Component::clear_summary() {
  if (summary_ != NULL) summary_->Clear();
  clear_has_summary();
}
inline const ::apollo::monitor::ComponentStatus& Component::_internal_summary() const {
  return *summary_;
}
inline const ::apollo::monitor::ComponentStatus& Component::summary() const {
  const ::apollo::monitor::ComponentStatus* p = summary_;
  // @@protoc_insertion_point(field_get:apollo.monitor.Component.summary)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::monitor::ComponentStatus*>(
      &::apollo::monitor::_ComponentStatus_default_instance_);
}
inline ::apollo::monitor::ComponentStatus* Component::release_summary() {
  // @@protoc_insertion_point(field_release:apollo.monitor.Component.summary)
  clear_has_summary();
  ::apollo::monitor::ComponentStatus* temp = summary_;
  summary_ = NULL;
  return temp;
}
inline ::apollo::monitor::ComponentStatus* Component::mutable_summary() {
  set_has_summary();
  if (summary_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::monitor::ComponentStatus>(GetArenaNoVirtual());
    summary_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.monitor.Component.summary)
  return summary_;
}
inline void Component::set_allocated_summary(::apollo::monitor::ComponentStatus* summary) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete summary_;
  }
  if (summary) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      summary = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, summary, submessage_arena);
    }
    set_has_summary();
  } else {
    clear_has_summary();
  }
  summary_ = summary;
  // @@protoc_insertion_point(field_set_allocated:apollo.monitor.Component.summary)
}

// optional .apollo.monitor.ComponentStatus process_status = 2;
inline bool Component::has_process_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Component::set_has_process_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Component::clear_has_process_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Component::clear_process_status() {
  if (process_status_ != NULL) process_status_->Clear();
  clear_has_process_status();
}
inline const ::apollo::monitor::ComponentStatus& Component::_internal_process_status() const {
  return *process_status_;
}
inline const ::apollo::monitor::ComponentStatus& Component::process_status() const {
  const ::apollo::monitor::ComponentStatus* p = process_status_;
  // @@protoc_insertion_point(field_get:apollo.monitor.Component.process_status)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::monitor::ComponentStatus*>(
      &::apollo::monitor::_ComponentStatus_default_instance_);
}
inline ::apollo::monitor::ComponentStatus* Component::release_process_status() {
  // @@protoc_insertion_point(field_release:apollo.monitor.Component.process_status)
  clear_has_process_status();
  ::apollo::monitor::ComponentStatus* temp = process_status_;
  process_status_ = NULL;
  return temp;
}
inline ::apollo::monitor::ComponentStatus* Component::mutable_process_status() {
  set_has_process_status();
  if (process_status_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::monitor::ComponentStatus>(GetArenaNoVirtual());
    process_status_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.monitor.Component.process_status)
  return process_status_;
}
inline void Component::set_allocated_process_status(::apollo::monitor::ComponentStatus* process_status) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete process_status_;
  }
  if (process_status) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      process_status = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, process_status, submessage_arena);
    }
    set_has_process_status();
  } else {
    clear_has_process_status();
  }
  process_status_ = process_status;
  // @@protoc_insertion_point(field_set_allocated:apollo.monitor.Component.process_status)
}

// optional .apollo.monitor.ComponentStatus channel_status = 3;
inline bool Component::has_channel_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Component::set_has_channel_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Component::clear_has_channel_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Component::clear_channel_status() {
  if (channel_status_ != NULL) channel_status_->Clear();
  clear_has_channel_status();
}
inline const ::apollo::monitor::ComponentStatus& Component::_internal_channel_status() const {
  return *channel_status_;
}
inline const ::apollo::monitor::ComponentStatus& Component::channel_status() const {
  const ::apollo::monitor::ComponentStatus* p = channel_status_;
  // @@protoc_insertion_point(field_get:apollo.monitor.Component.channel_status)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::monitor::ComponentStatus*>(
      &::apollo::monitor::_ComponentStatus_default_instance_);
}
inline ::apollo::monitor::ComponentStatus* Component::release_channel_status() {
  // @@protoc_insertion_point(field_release:apollo.monitor.Component.channel_status)
  clear_has_channel_status();
  ::apollo::monitor::ComponentStatus* temp = channel_status_;
  channel_status_ = NULL;
  return temp;
}
inline ::apollo::monitor::ComponentStatus* Component::mutable_channel_status() {
  set_has_channel_status();
  if (channel_status_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::monitor::ComponentStatus>(GetArenaNoVirtual());
    channel_status_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.monitor.Component.channel_status)
  return channel_status_;
}
inline void Component::set_allocated_channel_status(::apollo::monitor::ComponentStatus* channel_status) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete channel_status_;
  }
  if (channel_status) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      channel_status = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, channel_status, submessage_arena);
    }
    set_has_channel_status();
  } else {
    clear_has_channel_status();
  }
  channel_status_ = channel_status;
  // @@protoc_insertion_point(field_set_allocated:apollo.monitor.Component.channel_status)
}

// optional .apollo.monitor.ComponentStatus resource_status = 4;
inline bool Component::has_resource_status() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Component::set_has_resource_status() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Component::clear_has_resource_status() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Component::clear_resource_status() {
  if (resource_status_ != NULL) resource_status_->Clear();
  clear_has_resource_status();
}
inline const ::apollo::monitor::ComponentStatus& Component::_internal_resource_status() const {
  return *resource_status_;
}
inline const ::apollo::monitor::ComponentStatus& Component::resource_status() const {
  const ::apollo::monitor::ComponentStatus* p = resource_status_;
  // @@protoc_insertion_point(field_get:apollo.monitor.Component.resource_status)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::monitor::ComponentStatus*>(
      &::apollo::monitor::_ComponentStatus_default_instance_);
}
inline ::apollo::monitor::ComponentStatus* Component::release_resource_status() {
  // @@protoc_insertion_point(field_release:apollo.monitor.Component.resource_status)
  clear_has_resource_status();
  ::apollo::monitor::ComponentStatus* temp = resource_status_;
  resource_status_ = NULL;
  return temp;
}
inline ::apollo::monitor::ComponentStatus* Component::mutable_resource_status() {
  set_has_resource_status();
  if (resource_status_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::monitor::ComponentStatus>(GetArenaNoVirtual());
    resource_status_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.monitor.Component.resource_status)
  return resource_status_;
}
inline void Component::set_allocated_resource_status(::apollo::monitor::ComponentStatus* resource_status) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete resource_status_;
  }
  if (resource_status) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      resource_status = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, resource_status, submessage_arena);
    }
    set_has_resource_status();
  } else {
    clear_has_resource_status();
  }
  resource_status_ = resource_status;
  // @@protoc_insertion_point(field_set_allocated:apollo.monitor.Component.resource_status)
}

// optional .apollo.monitor.ComponentStatus other_status = 5;
inline bool Component::has_other_status() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Component::set_has_other_status() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Component::clear_has_other_status() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Component::clear_other_status() {
  if (other_status_ != NULL) other_status_->Clear();
  clear_has_other_status();
}
inline const ::apollo::monitor::ComponentStatus& Component::_internal_other_status() const {
  return *other_status_;
}
inline const ::apollo::monitor::ComponentStatus& Component::other_status() const {
  const ::apollo::monitor::ComponentStatus* p = other_status_;
  // @@protoc_insertion_point(field_get:apollo.monitor.Component.other_status)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::monitor::ComponentStatus*>(
      &::apollo::monitor::_ComponentStatus_default_instance_);
}
inline ::apollo::monitor::ComponentStatus* Component::release_other_status() {
  // @@protoc_insertion_point(field_release:apollo.monitor.Component.other_status)
  clear_has_other_status();
  ::apollo::monitor::ComponentStatus* temp = other_status_;
  other_status_ = NULL;
  return temp;
}
inline ::apollo::monitor::ComponentStatus* Component::mutable_other_status() {
  set_has_other_status();
  if (other_status_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::monitor::ComponentStatus>(GetArenaNoVirtual());
    other_status_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.monitor.Component.other_status)
  return other_status_;
}
inline void Component::set_allocated_other_status(::apollo::monitor::ComponentStatus* other_status) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete other_status_;
  }
  if (other_status) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      other_status = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, other_status, submessage_arena);
    }
    set_has_other_status();
  } else {
    clear_has_other_status();
  }
  other_status_ = other_status;
  // @@protoc_insertion_point(field_set_allocated:apollo.monitor.Component.other_status)
}

// optional .apollo.monitor.ComponentStatus module_status = 6;
inline bool Component::has_module_status() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Component::set_has_module_status() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Component::clear_has_module_status() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Component::clear_module_status() {
  if (module_status_ != NULL) module_status_->Clear();
  clear_has_module_status();
}
inline const ::apollo::monitor::ComponentStatus& Component::_internal_module_status() const {
  return *module_status_;
}
inline const ::apollo::monitor::ComponentStatus& Component::module_status() const {
  const ::apollo::monitor::ComponentStatus* p = module_status_;
  // @@protoc_insertion_point(field_get:apollo.monitor.Component.module_status)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::monitor::ComponentStatus*>(
      &::apollo::monitor::_ComponentStatus_default_instance_);
}
inline ::apollo::monitor::ComponentStatus* Component::release_module_status() {
  // @@protoc_insertion_point(field_release:apollo.monitor.Component.module_status)
  clear_has_module_status();
  ::apollo::monitor::ComponentStatus* temp = module_status_;
  module_status_ = NULL;
  return temp;
}
inline ::apollo::monitor::ComponentStatus* Component::mutable_module_status() {
  set_has_module_status();
  if (module_status_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::monitor::ComponentStatus>(GetArenaNoVirtual());
    module_status_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.monitor.Component.module_status)
  return module_status_;
}
inline void Component::set_allocated_module_status(::apollo::monitor::ComponentStatus* module_status) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete module_status_;
  }
  if (module_status) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      module_status = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, module_status, submessage_arena);
    }
    set_has_module_status();
  } else {
    clear_has_module_status();
  }
  module_status_ = module_status;
  // @@protoc_insertion_point(field_set_allocated:apollo.monitor.Component.module_status)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SystemStatus

// optional .apollo.common.Header header = 1;
inline bool SystemStatus::has_header() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SystemStatus::set_has_header() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SystemStatus::clear_has_header() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::apollo::common::Header& SystemStatus::_internal_header() const {
  return *header_;
}
inline const ::apollo::common::Header& SystemStatus::header() const {
  const ::apollo::common::Header* p = header_;
  // @@protoc_insertion_point(field_get:apollo.monitor.SystemStatus.header)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::Header*>(
      &::apollo::common::_Header_default_instance_);
}
inline ::apollo::common::Header* SystemStatus::release_header() {
  // @@protoc_insertion_point(field_release:apollo.monitor.SystemStatus.header)
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::apollo::common::Header* SystemStatus::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.monitor.SystemStatus.header)
  return header_;
}
inline void SystemStatus::set_allocated_header(::apollo::common::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    set_has_header();
  } else {
    clear_has_header();
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:apollo.monitor.SystemStatus.header)
}

// map<string, .apollo.monitor.ComponentStatus> hmi_modules = 7;
inline int SystemStatus::hmi_modules_size() const {
  return hmi_modules_.size();
}
inline void SystemStatus::clear_hmi_modules() {
  hmi_modules_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::apollo::monitor::ComponentStatus >&
SystemStatus::hmi_modules() const {
  // @@protoc_insertion_point(field_map:apollo.monitor.SystemStatus.hmi_modules)
  return hmi_modules_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::apollo::monitor::ComponentStatus >*
SystemStatus::mutable_hmi_modules() {
  // @@protoc_insertion_point(field_mutable_map:apollo.monitor.SystemStatus.hmi_modules)
  return hmi_modules_.MutableMap();
}

// map<string, .apollo.monitor.Component> components = 8;
inline int SystemStatus::components_size() const {
  return components_.size();
}
inline void SystemStatus::clear_components() {
  components_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::apollo::monitor::Component >&
SystemStatus::components() const {
  // @@protoc_insertion_point(field_map:apollo.monitor.SystemStatus.components)
  return components_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::apollo::monitor::Component >*
SystemStatus::mutable_components() {
  // @@protoc_insertion_point(field_mutable_map:apollo.monitor.SystemStatus.components)
  return components_.MutableMap();
}

// optional string passenger_msg = 4;
inline bool SystemStatus::has_passenger_msg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SystemStatus::set_has_passenger_msg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SystemStatus::clear_has_passenger_msg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SystemStatus::clear_passenger_msg() {
  passenger_msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_passenger_msg();
}
inline const ::std::string& SystemStatus::passenger_msg() const {
  // @@protoc_insertion_point(field_get:apollo.monitor.SystemStatus.passenger_msg)
  return passenger_msg_.GetNoArena();
}
inline void SystemStatus::set_passenger_msg(const ::std::string& value) {
  set_has_passenger_msg();
  passenger_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.monitor.SystemStatus.passenger_msg)
}
#if LANG_CXX11
inline void SystemStatus::set_passenger_msg(::std::string&& value) {
  set_has_passenger_msg();
  passenger_msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.monitor.SystemStatus.passenger_msg)
}
#endif
inline void SystemStatus::set_passenger_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_passenger_msg();
  passenger_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.monitor.SystemStatus.passenger_msg)
}
inline void SystemStatus::set_passenger_msg(const char* value, size_t size) {
  set_has_passenger_msg();
  passenger_msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.monitor.SystemStatus.passenger_msg)
}
inline ::std::string* SystemStatus::mutable_passenger_msg() {
  set_has_passenger_msg();
  // @@protoc_insertion_point(field_mutable:apollo.monitor.SystemStatus.passenger_msg)
  return passenger_msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SystemStatus::release_passenger_msg() {
  // @@protoc_insertion_point(field_release:apollo.monitor.SystemStatus.passenger_msg)
  if (!has_passenger_msg()) {
    return NULL;
  }
  clear_has_passenger_msg();
  return passenger_msg_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SystemStatus::set_allocated_passenger_msg(::std::string* passenger_msg) {
  if (passenger_msg != NULL) {
    set_has_passenger_msg();
  } else {
    clear_has_passenger_msg();
  }
  passenger_msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), passenger_msg);
  // @@protoc_insertion_point(field_set_allocated:apollo.monitor.SystemStatus.passenger_msg)
}

// optional double safety_mode_trigger_time = 5;
inline bool SystemStatus::has_safety_mode_trigger_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SystemStatus::set_has_safety_mode_trigger_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SystemStatus::clear_has_safety_mode_trigger_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SystemStatus::clear_safety_mode_trigger_time() {
  safety_mode_trigger_time_ = 0;
  clear_has_safety_mode_trigger_time();
}
inline double SystemStatus::safety_mode_trigger_time() const {
  // @@protoc_insertion_point(field_get:apollo.monitor.SystemStatus.safety_mode_trigger_time)
  return safety_mode_trigger_time_;
}
inline void SystemStatus::set_safety_mode_trigger_time(double value) {
  set_has_safety_mode_trigger_time();
  safety_mode_trigger_time_ = value;
  // @@protoc_insertion_point(field_set:apollo.monitor.SystemStatus.safety_mode_trigger_time)
}

// optional bool require_emergency_stop = 6;
inline bool SystemStatus::has_require_emergency_stop() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SystemStatus::set_has_require_emergency_stop() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SystemStatus::clear_has_require_emergency_stop() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SystemStatus::clear_require_emergency_stop() {
  require_emergency_stop_ = false;
  clear_has_require_emergency_stop();
}
inline bool SystemStatus::require_emergency_stop() const {
  // @@protoc_insertion_point(field_get:apollo.monitor.SystemStatus.require_emergency_stop)
  return require_emergency_stop_;
}
inline void SystemStatus::set_require_emergency_stop(bool value) {
  set_has_require_emergency_stop();
  require_emergency_stop_ = value;
  // @@protoc_insertion_point(field_set:apollo.monitor.SystemStatus.require_emergency_stop)
}

// optional bool is_realtime_in_simulation = 9;
inline bool SystemStatus::has_is_realtime_in_simulation() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SystemStatus::set_has_is_realtime_in_simulation() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SystemStatus::clear_has_is_realtime_in_simulation() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SystemStatus::clear_is_realtime_in_simulation() {
  is_realtime_in_simulation_ = false;
  clear_has_is_realtime_in_simulation();
}
inline bool SystemStatus::is_realtime_in_simulation() const {
  // @@protoc_insertion_point(field_get:apollo.monitor.SystemStatus.is_realtime_in_simulation)
  return is_realtime_in_simulation_;
}
inline void SystemStatus::set_is_realtime_in_simulation(bool value) {
  set_has_is_realtime_in_simulation();
  is_realtime_in_simulation_ = value;
  // @@protoc_insertion_point(field_set:apollo.monitor.SystemStatus.is_realtime_in_simulation)
}

// map<string, .apollo.monitor.ComponentStatus> other_components = 10;
inline int SystemStatus::other_components_size() const {
  return other_components_.size();
}
inline void SystemStatus::clear_other_components() {
  other_components_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::apollo::monitor::ComponentStatus >&
SystemStatus::other_components() const {
  // @@protoc_insertion_point(field_map:apollo.monitor.SystemStatus.other_components)
  return other_components_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::apollo::monitor::ComponentStatus >*
SystemStatus::mutable_other_components() {
  // @@protoc_insertion_point(field_mutable_map:apollo.monitor.SystemStatus.other_components)
  return other_components_.MutableMap();
}

// map<string, .apollo.monitor.Component> global_components = 11;
inline int SystemStatus::global_components_size() const {
  return global_components_.size();
}
inline void SystemStatus::clear_global_components() {
  global_components_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::apollo::monitor::Component >&
SystemStatus::global_components() const {
  // @@protoc_insertion_point(field_map:apollo.monitor.SystemStatus.global_components)
  return global_components_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::apollo::monitor::Component >*
SystemStatus::mutable_global_components() {
  // @@protoc_insertion_point(field_mutable_map:apollo.monitor.SystemStatus.global_components)
  return global_components_.MutableMap();
}

// optional bool detect_immediately = 12 [default = false];
inline bool SystemStatus::has_detect_immediately() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SystemStatus::set_has_detect_immediately() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SystemStatus::clear_has_detect_immediately() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SystemStatus::clear_detect_immediately() {
  detect_immediately_ = false;
  clear_has_detect_immediately();
}
inline bool SystemStatus::detect_immediately() const {
  // @@protoc_insertion_point(field_get:apollo.monitor.SystemStatus.detect_immediately)
  return detect_immediately_;
}
inline void SystemStatus::set_detect_immediately(bool value) {
  set_has_detect_immediately();
  detect_immediately_ = value;
  // @@protoc_insertion_point(field_set:apollo.monitor.SystemStatus.detect_immediately)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace monitor
}  // namespace apollo

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::monitor::ComponentStatus_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::monitor::ComponentStatus_Status>() {
  return ::apollo::monitor::ComponentStatus_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_modules_2fcommon_5fmsgs_2fmonitor_5fmsgs_2fsystem_5fstatus_2eproto
