[general]
wts_file =
engine_file = /workspaces/CodexOpen/install/bin/model/yolov8/yolov8s.engine
;engine_file = /workspaces/CodexOpen/install/bin/model/yolov8/yolov8s-int8.engine
;engine_file = /workspaces/CodexOpen/install/bin/model/yolov5/yolov5s.engine
onnx_file =
