[general]
rosbag_path = /workspaces/CodexOpenExtraData/raw_data/miluo
rosbag_name = 2026-01-28-09-31-37
;rosbag_path = /workspaces/CodexOpenExtraData/raw_data
;rosbag_name = 2026-03-18-21-13-40
;rosbag_name = /workspaces/CodexOpenExtraData
;rosbag_name = 2024-09-23-10-39-02
; rosbag_path = /workspaces/CodexOpenExtraData/ros2/robot164
; rosbag_name = rosbag2_1970_01_12-07_25_18
; rosbag_name = rosbag2_1970_01_16-14_43_52
b_save_data = 1
save_path = /workspaces/CodexOpenExtraData/data
;save_path = /workspaces/CodexOpenExtraData
b_compensation_cloud = 0
b_lt_none_rt = 1
b_bin_or_pcd = 1
b_jpg_or_png = 0
b_txt_or_pcd = 0
prepare_data_num = -1
sample_interval = 12
useless_time = 1

[topics]
b_do_undistort = 1

[calibration]
calib_file_dir = /workspaces/CodexOpen/install/common/GreenMengShi193/calib

[device_names]
;ImuType = mid360
LidarType = rs128
;LidarType = m1p
;LidarType = mid360
; CameraName = ar0231_front,ar0231_left_front,ar0231_right_front
CameraName = ar0231_front,ar0231_front_left,ar0231_front_right
InfraName = p12_front,p12_left_front,p12_right_front
StarName = ar0231_front_120
;RadarType = ars408
RadarType = esr
Radar4DType = ars548