[sensors]
LocalPose = 0
GlobalPose = 0
ImuData = 0
Camera = 0
Infra = 0
Star = 0
Radar = 0
Radar4D = 0
Lidar = 1

[topics]
topic_global_pose_sub = /self_state/GlobalPose
topic_local_pose_sub = /self_state/LocalPose
topic_imu_data_sub = /sensor/Imu
; topic_imu_data_sub = /livox/imu

; b_difop = 0
b_difop = 1
topic_lidar_ori_sub = /sensor/RS128Packets_tztek
topic_lidar_difop_sub = /sensor/RS128Packets_tztek_difop
topic_lidar_sub = /rslidar_points
;topic_lidar_sub = /hesai/pandar_points
; topic_lidar_sub = /livox/lidar

b_compressed = 1
topic_camera_sub_1 = /sensor/image/ar0231_front/compressed
; topic_camera_sub_1 = /iRobot/sensor/camera/ar0231/front/compressed/
;topic_camera_sub_1 = /GreenCat52/sensor/camera/imx390/front_60/front/compressed
; topic_camera_sub_1 = /camera/camera/color/image_raw
topic_camera_sub_2 = /sensor/image/ar0231_frontleft/compressed
;topic_camera_sub_2 = /camera/fisheye/compressed
; topic_camera_sub_2 = /camera/camera/depth/image_rect_raw
topic_camera_sub_3 = /sensor/image/ar0231_frontright/compressed
;topic_camera_sub_3 = /camera/image_test/compressed
topic_infra_sub_1 = /sensor/infra/ir_front/compressed
topic_infra_sub_2 = /sensor/infra/ir_leftfront/compressed
topic_infra_sub_3 = /sensor/infra/ir_rightfront/compressed
topic_star_sub_1 = /sensor/star/ar0231_front/compressed
topic_star_sub_2 = /sensor/star/ar0231_left_front/compressed
topic_star_sub_3 = /sensor/star/ar0231_right_front/compressed

topic_radar_sub = /sensor/ESR_Radar_objects
;topic_radar4d_sub_1 = /ars548_process/detection_list
;topic_radar4d_sub_1 = /sensor/radar/ars548_front/detection_list
topic_radar4d_sub_1 = /GreenMengShi193/sensor/radar/ars548/front/detection_list
topic_radar4d_sub_2 = /GreenMengShi193/sensor/radar/ars548/front_left/detection_list
topic_radar4d_sub_3 = /GreenMengShi193/sensor/radar/ars548/front_right/detection_list