[general]
; root_path = /workspaces/CodexOpenExtraData/DataSet/2026-04-16
; file_name = 2026-04-16-17-13-20
root_path = /workspaces/CodexOpenExtraData/DataSet/1970-01-12
file_name = 1970-01-12-07-25-18
start_time = 0
end_time = 0
current_time = 0
pause_time = 0.1
b_compensation_cloud = 0
b_lt_none_rt = 1
b_bin_or_pcd = 1
b_undistort = 1
b_jpg_or_png = 0
b_txt_or_pcd = 0
b_imu_vec = 1

[sensors]
LocalPose = 0
GlobalPose = 0
ImuData = 1
Camera = 0
Infra = 0
Star = 0
Radar = 0
Radar4D = 0
Lidar = 1

[topics]
b_do_undistort = 0

[calibration]
;calib_file_dir = /workspaces/CodexOpen/install/common/GreenMengShi193/calib
calib_file_dir = /workspaces/CodexOpen/install/common/iRobot193/calib

[device_names]
;LidarType = rs128
LidarType = mid360
CameraName = ar0231_front,ar0231_left_front,ar0231_right_front
InfraName = p12_front,p12_left_front,p12_right_front
StarName = ar0231_front_120