[general]
; lidar coords to ground coords
ref_height = -2.5
hanging_z = 3.0
; half height of the wheels ; 主要用于设置 偏移值；
mean_z_thresh  = 0.8
delta_z_thresh = 0.1
b_use_legacy = 1
b_use_gaussian = 0
b_gravity = 1
; b_gravity = 0

[map]
far_resolution = 0.6
middle_resolution = 0.4
near_resolution = 0.3
map_resolution = 0.2
map_rows = 512
map_cols = 512

[min_bound]
x = -5
y = -3.5
z = -5

[max_bound]
x = 6
y = 3.5
z = 2

[visualize]
b_show_color_point = 0

[calibration]
; camera_calib_file_path = /workspaces/CodexOpen/install/common/GreenMengShi193/calib/ar0231_front.ini
camera_calib_file_path = /workspaces/CodexOpen/install/common/iRobot193/calib/s11a60_front_left.ini
gravity_lidar_calib_file_path = /workspaces/CodexOpen/install/common/iRobot193/calib/lidar_to_gravity.ini
