// Generated by gencpp from file world_state/ROAD_OBJ.msg
// DO NOT EDIT!


#ifndef WORLD_STATE_MESSAGE_ROAD_OBJ_H
#define WORLD_STATE_MESSAGE_ROAD_OBJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace world_state
{
template <class ContainerAllocator>
struct ROAD_OBJ_
{
  typedef ROAD_OBJ_<ContainerAllocator> Type;

  ROAD_OBJ_()
    : CenterPtNum(0)
    , LeftPtNum(0)
    , RightPtNum(0)
    , effectiveCenterLinePoint(0)
    , CenterLinePtX()
    , CenterLinePtY()
    , effectiveLeftEdgePoint(0)
    , LeftEdgePtX()
    , LeftEdgePtY()
    , effectiveRightEdgePoint(0)
    , RightEdgePtX()
    , RightEdgePtY()  {
      CenterLinePtX.assign(0.0);

      CenterLinePtY.assign(0.0);

      LeftEdgePtX.assign(0.0);

      LeftEdgePtY.assign(0.0);

      RightEdgePtX.assign(0.0);

      RightEdgePtY.assign(0.0);
  }
  ROAD_OBJ_(const ContainerAllocator& _alloc)
    : CenterPtNum(0)
    , LeftPtNum(0)
    , RightPtNum(0)
    , effectiveCenterLinePoint(0)
    , CenterLinePtX()
    , CenterLinePtY()
    , effectiveLeftEdgePoint(0)
    , LeftEdgePtX()
    , LeftEdgePtY()
    , effectiveRightEdgePoint(0)
    , RightEdgePtX()
    , RightEdgePtY()  {
  (void)_alloc;
      CenterLinePtX.assign(0.0);

      CenterLinePtY.assign(0.0);

      LeftEdgePtX.assign(0.0);

      LeftEdgePtY.assign(0.0);

      RightEdgePtX.assign(0.0);

      RightEdgePtY.assign(0.0);
  }



   typedef int32_t _CenterPtNum_type;
  _CenterPtNum_type CenterPtNum;

   typedef int32_t _LeftPtNum_type;
  _LeftPtNum_type LeftPtNum;

   typedef int32_t _RightPtNum_type;
  _RightPtNum_type RightPtNum;

   typedef int32_t _effectiveCenterLinePoint_type;
  _effectiveCenterLinePoint_type effectiveCenterLinePoint;

   typedef boost::array<double, 50>  _CenterLinePtX_type;
  _CenterLinePtX_type CenterLinePtX;

   typedef boost::array<double, 50>  _CenterLinePtY_type;
  _CenterLinePtY_type CenterLinePtY;

   typedef int32_t _effectiveLeftEdgePoint_type;
  _effectiveLeftEdgePoint_type effectiveLeftEdgePoint;

   typedef boost::array<double, 50>  _LeftEdgePtX_type;
  _LeftEdgePtX_type LeftEdgePtX;

   typedef boost::array<double, 50>  _LeftEdgePtY_type;
  _LeftEdgePtY_type LeftEdgePtY;

   typedef int32_t _effectiveRightEdgePoint_type;
  _effectiveRightEdgePoint_type effectiveRightEdgePoint;

   typedef boost::array<double, 50>  _RightEdgePtX_type;
  _RightEdgePtX_type RightEdgePtX;

   typedef boost::array<double, 50>  _RightEdgePtY_type;
  _RightEdgePtY_type RightEdgePtY;





  typedef boost::shared_ptr< ::world_state::ROAD_OBJ_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::world_state::ROAD_OBJ_<ContainerAllocator> const> ConstPtr;

}; // struct ROAD_OBJ_

typedef ::world_state::ROAD_OBJ_<std::allocator<void> > ROAD_OBJ;

typedef boost::shared_ptr< ::world_state::ROAD_OBJ > ROAD_OBJPtr;
typedef boost::shared_ptr< ::world_state::ROAD_OBJ const> ROAD_OBJConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::world_state::ROAD_OBJ_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::world_state::ROAD_OBJ_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::world_state::ROAD_OBJ_<ContainerAllocator1> & lhs, const ::world_state::ROAD_OBJ_<ContainerAllocator2> & rhs)
{
  return lhs.CenterPtNum == rhs.CenterPtNum &&
    lhs.LeftPtNum == rhs.LeftPtNum &&
    lhs.RightPtNum == rhs.RightPtNum &&
    lhs.effectiveCenterLinePoint == rhs.effectiveCenterLinePoint &&
    lhs.CenterLinePtX == rhs.CenterLinePtX &&
    lhs.CenterLinePtY == rhs.CenterLinePtY &&
    lhs.effectiveLeftEdgePoint == rhs.effectiveLeftEdgePoint &&
    lhs.LeftEdgePtX == rhs.LeftEdgePtX &&
    lhs.LeftEdgePtY == rhs.LeftEdgePtY &&
    lhs.effectiveRightEdgePoint == rhs.effectiveRightEdgePoint &&
    lhs.RightEdgePtX == rhs.RightEdgePtX &&
    lhs.RightEdgePtY == rhs.RightEdgePtY;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::world_state::ROAD_OBJ_<ContainerAllocator1> & lhs, const ::world_state::ROAD_OBJ_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace world_state

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::world_state::ROAD_OBJ_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::world_state::ROAD_OBJ_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_state::ROAD_OBJ_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::world_state::ROAD_OBJ_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_state::ROAD_OBJ_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::world_state::ROAD_OBJ_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::world_state::ROAD_OBJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9d50f1818e01c056abd133dc275f35f";
  }

  static const char* value(const ::world_state::ROAD_OBJ_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9d50f1818e01c05ULL;
  static const uint64_t static_value2 = 0x6abd133dc275f35fULL;
};

template<class ContainerAllocator>
struct DataType< ::world_state::ROAD_OBJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "world_state/ROAD_OBJ";
  }

  static const char* value(const ::world_state::ROAD_OBJ_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::world_state::ROAD_OBJ_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 CenterPtNum\n"
"int32 LeftPtNum\n"
"int32 RightPtNum\n"
"int32 effectiveCenterLinePoint\n"
"float64[50] CenterLinePtX   # in m\n"
"float64[50] CenterLinePtY   # in m\n"
"int32 effectiveLeftEdgePoint\n"
"float64[50] LeftEdgePtX     # in m\n"
"float64[50] LeftEdgePtY     # in m\n"
"int32 effectiveRightEdgePoint\n"
"float64[50] RightEdgePtX    # in m\n"
"float64[50] RightEdgePtY    # in m    \n"
;
  }

  static const char* value(const ::world_state::ROAD_OBJ_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::world_state::ROAD_OBJ_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.CenterPtNum);
      stream.next(m.LeftPtNum);
      stream.next(m.RightPtNum);
      stream.next(m.effectiveCenterLinePoint);
      stream.next(m.CenterLinePtX);
      stream.next(m.CenterLinePtY);
      stream.next(m.effectiveLeftEdgePoint);
      stream.next(m.LeftEdgePtX);
      stream.next(m.LeftEdgePtY);
      stream.next(m.effectiveRightEdgePoint);
      stream.next(m.RightEdgePtX);
      stream.next(m.RightEdgePtY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROAD_OBJ_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::world_state::ROAD_OBJ_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::world_state::ROAD_OBJ_<ContainerAllocator>& v)
  {
    s << indent << "CenterPtNum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.CenterPtNum);
    s << indent << "LeftPtNum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.LeftPtNum);
    s << indent << "RightPtNum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.RightPtNum);
    s << indent << "effectiveCenterLinePoint: ";
    Printer<int32_t>::stream(s, indent + "  ", v.effectiveCenterLinePoint);
    s << indent << "CenterLinePtX[]" << std::endl;
    for (size_t i = 0; i < v.CenterLinePtX.size(); ++i)
    {
      s << indent << "  CenterLinePtX[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.CenterLinePtX[i]);
    }
    s << indent << "CenterLinePtY[]" << std::endl;
    for (size_t i = 0; i < v.CenterLinePtY.size(); ++i)
    {
      s << indent << "  CenterLinePtY[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.CenterLinePtY[i]);
    }
    s << indent << "effectiveLeftEdgePoint: ";
    Printer<int32_t>::stream(s, indent + "  ", v.effectiveLeftEdgePoint);
    s << indent << "LeftEdgePtX[]" << std::endl;
    for (size_t i = 0; i < v.LeftEdgePtX.size(); ++i)
    {
      s << indent << "  LeftEdgePtX[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.LeftEdgePtX[i]);
    }
    s << indent << "LeftEdgePtY[]" << std::endl;
    for (size_t i = 0; i < v.LeftEdgePtY.size(); ++i)
    {
      s << indent << "  LeftEdgePtY[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.LeftEdgePtY[i]);
    }
    s << indent << "effectiveRightEdgePoint: ";
    Printer<int32_t>::stream(s, indent + "  ", v.effectiveRightEdgePoint);
    s << indent << "RightEdgePtX[]" << std::endl;
    for (size_t i = 0; i < v.RightEdgePtX.size(); ++i)
    {
      s << indent << "  RightEdgePtX[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.RightEdgePtX[i]);
    }
    s << indent << "RightEdgePtY[]" << std::endl;
    for (size_t i = 0; i < v.RightEdgePtY.size(); ++i)
    {
      s << indent << "  RightEdgePtY[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.RightEdgePtY[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WORLD_STATE_MESSAGE_ROAD_OBJ_H
