// Generated by gencpp from file behavior/ReferencePathResponse.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_MESSAGE_REFERENCEPATHRESPONSE_H
#define BEHAVIOR_MESSAGE_REFERENCEPATHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace behavior
{
template <class ContainerAllocator>
struct ReferencePathResponse_
{
  typedef ReferencePathResponse_<ContainerAllocator> Type;

  ReferencePathResponse_()
    : Points()
    , effectPointsNum(0)  {
    }
  ReferencePathResponse_(const ContainerAllocator& _alloc)
    : Points(_alloc)
    , effectPointsNum(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose2D_<ContainerAllocator> >> _Points_type;
  _Points_type Points;

   typedef int32_t _effectPointsNum_type;
  _effectPointsNum_type effectPointsNum;





  typedef boost::shared_ptr< ::behavior::ReferencePathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior::ReferencePathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReferencePathResponse_

typedef ::behavior::ReferencePathResponse_<std::allocator<void> > ReferencePathResponse;

typedef boost::shared_ptr< ::behavior::ReferencePathResponse > ReferencePathResponsePtr;
typedef boost::shared_ptr< ::behavior::ReferencePathResponse const> ReferencePathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior::ReferencePathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior::ReferencePathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior::ReferencePathResponse_<ContainerAllocator1> & lhs, const ::behavior::ReferencePathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Points == rhs.Points &&
    lhs.effectPointsNum == rhs.effectPointsNum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior::ReferencePathResponse_<ContainerAllocator1> & lhs, const ::behavior::ReferencePathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior::ReferencePathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior::ReferencePathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior::ReferencePathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior::ReferencePathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior::ReferencePathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior::ReferencePathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior::ReferencePathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2a40bafc0c8d63301457f026d9e3c0c";
  }

  static const char* value(const ::behavior::ReferencePathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2a40bafc0c8d633ULL;
  static const uint64_t static_value2 = 0x01457f026d9e3c0cULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior::ReferencePathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior/ReferencePathResponse";
  }

  static const char* value(const ::behavior::ReferencePathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior::ReferencePathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D[]  Points\n"
"int32 effectPointsNum\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::behavior::ReferencePathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior::ReferencePathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Points);
      stream.next(m.effectPointsNum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReferencePathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior::ReferencePathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior::ReferencePathResponse_<ContainerAllocator>& v)
  {
    s << indent << "Points[]" << std::endl;
    for (size_t i = 0; i < v.Points.size(); ++i)
    {
      s << indent << "  Points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.Points[i]);
    }
    s << indent << "effectPointsNum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.effectPointsNum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_MESSAGE_REFERENCEPATHRESPONSE_H
