<?xml version="1.0"?>
<package format="3">
  <name>data_processor</name>
  <version>0.0.0</version>
  <description>data processor module</description>

  <maintainer email="you@todo.todo">you</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>rosbag2_cpp</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>

</package>
