// Generated by gencpp from file ars548_process/AccelerationLateralCog.msg
// DO NOT EDIT!


#ifndef ARS548_PROCESS_MESSAGE_ACCELERATIONLATERALCOG_H
#define ARS548_PROCESS_MESSAGE_ACCELERATIONLATERALCOG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ars548_process
{
template <class ContainerAllocator>
struct AccelerationLateralCog_
{
  typedef AccelerationLateralCog_<ContainerAllocator> Type;

  AccelerationLateralCog_()
    : header()
    , acceleration_lateral_err_amp(0.0)
    , acceleration_lateral_err_amp_invalid_flag(0)
    , qualifier_acceleration_lateral(0)
    , acceleration_lateral(0.0)
    , acceleration_lateral_invalid_flag(0)
    , acceleration_lateral_event_data_qualifier(0)  {
    }
  AccelerationLateralCog_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acceleration_lateral_err_amp(0.0)
    , acceleration_lateral_err_amp_invalid_flag(0)
    , qualifier_acceleration_lateral(0)
    , acceleration_lateral(0.0)
    , acceleration_lateral_invalid_flag(0)
    , acceleration_lateral_event_data_qualifier(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _acceleration_lateral_err_amp_type;
  _acceleration_lateral_err_amp_type acceleration_lateral_err_amp;

   typedef uint8_t _acceleration_lateral_err_amp_invalid_flag_type;
  _acceleration_lateral_err_amp_invalid_flag_type acceleration_lateral_err_amp_invalid_flag;

   typedef uint8_t _qualifier_acceleration_lateral_type;
  _qualifier_acceleration_lateral_type qualifier_acceleration_lateral;

   typedef float _acceleration_lateral_type;
  _acceleration_lateral_type acceleration_lateral;

   typedef uint8_t _acceleration_lateral_invalid_flag_type;
  _acceleration_lateral_invalid_flag_type acceleration_lateral_invalid_flag;

   typedef uint8_t _acceleration_lateral_event_data_qualifier_type;
  _acceleration_lateral_event_data_qualifier_type acceleration_lateral_event_data_qualifier;





  typedef boost::shared_ptr< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> const> ConstPtr;

}; // struct AccelerationLateralCog_

typedef ::ars548_process::AccelerationLateralCog_<std::allocator<void> > AccelerationLateralCog;

typedef boost::shared_ptr< ::ars548_process::AccelerationLateralCog > AccelerationLateralCogPtr;
typedef boost::shared_ptr< ::ars548_process::AccelerationLateralCog const> AccelerationLateralCogConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ars548_process::AccelerationLateralCog_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ars548_process::AccelerationLateralCog_<ContainerAllocator1> & lhs, const ::ars548_process::AccelerationLateralCog_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.acceleration_lateral_err_amp == rhs.acceleration_lateral_err_amp &&
    lhs.acceleration_lateral_err_amp_invalid_flag == rhs.acceleration_lateral_err_amp_invalid_flag &&
    lhs.qualifier_acceleration_lateral == rhs.qualifier_acceleration_lateral &&
    lhs.acceleration_lateral == rhs.acceleration_lateral &&
    lhs.acceleration_lateral_invalid_flag == rhs.acceleration_lateral_invalid_flag &&
    lhs.acceleration_lateral_event_data_qualifier == rhs.acceleration_lateral_event_data_qualifier;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ars548_process::AccelerationLateralCog_<ContainerAllocator1> & lhs, const ::ars548_process::AccelerationLateralCog_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ars548_process

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8928723b4c4efb12bd54eb493a4d1caa";
  }

  static const char* value(const ::ars548_process::AccelerationLateralCog_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8928723b4c4efb12ULL;
  static const uint64_t static_value2 = 0xbd54eb493a4d1caaULL;
};

template<class ContainerAllocator>
struct DataType< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ars548_process/AccelerationLateralCog";
  }

  static const char* value(const ::ars548_process::AccelerationLateralCog_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float32 acceleration_lateral_err_amp\n"
"uint8 acceleration_lateral_err_amp_invalid_flag\n"
"uint8 qualifier_acceleration_lateral\n"
"float32 acceleration_lateral\n"
"uint8 acceleration_lateral_invalid_flag\n"
"uint8 acceleration_lateral_event_data_qualifier\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ars548_process::AccelerationLateralCog_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acceleration_lateral_err_amp);
      stream.next(m.acceleration_lateral_err_amp_invalid_flag);
      stream.next(m.qualifier_acceleration_lateral);
      stream.next(m.acceleration_lateral);
      stream.next(m.acceleration_lateral_invalid_flag);
      stream.next(m.acceleration_lateral_event_data_qualifier);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AccelerationLateralCog_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ars548_process::AccelerationLateralCog_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ars548_process::AccelerationLateralCog_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acceleration_lateral_err_amp: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration_lateral_err_amp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acceleration_lateral_err_amp_invalid_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acceleration_lateral_err_amp_invalid_flag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "qualifier_acceleration_lateral: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.qualifier_acceleration_lateral);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acceleration_lateral: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration_lateral);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acceleration_lateral_invalid_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acceleration_lateral_invalid_flag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acceleration_lateral_event_data_qualifier: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acceleration_lateral_event_data_qualifier);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARS548_PROCESS_MESSAGE_ACCELERATIONLATERALCOG_H
