// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/common_msgs/task_manager_msgs/task_manager.proto

#include "modules/common_msgs/task_manager_msgs/task_manager.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fheader_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fheader_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Header;
}  // namespace protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fheader_2eproto
namespace protobuf_modules_2fcommon_5fmsgs_2fexternal_5fcommand_5fmsgs_2flane_5ffollow_5fcommand_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2fexternal_5fcommand_5fmsgs_2flane_5ffollow_5fcommand_2eproto ::google::protobuf::internal::SCCInfo<3> scc_info_LaneFollowCommand;
}  // namespace protobuf_modules_2fcommon_5fmsgs_2fexternal_5fcommand_5fmsgs_2flane_5ffollow_5fcommand_2eproto
namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto ::google::protobuf::internal::SCCInfo<4> scc_info_RoutingRequest;
}  // namespace protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto
namespace protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_CycleRoutingTask;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_ParkGoRoutingTask;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_ParkingRoutingTask;
}  // namespace protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto
namespace apollo {
namespace task_manager {
class CycleRoutingTaskDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CycleRoutingTask>
      _instance;
} _CycleRoutingTask_default_instance_;
class ParkingRoutingTaskDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ParkingRoutingTask>
      _instance;
} _ParkingRoutingTask_default_instance_;
class ParkGoRoutingTaskDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ParkGoRoutingTask>
      _instance;
} _ParkGoRoutingTask_default_instance_;
class TaskDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Task>
      _instance;
} _Task_default_instance_;
}  // namespace task_manager
}  // namespace apollo
namespace protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto {
static void InitDefaultsCycleRoutingTask() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::task_manager::_CycleRoutingTask_default_instance_;
    new (ptr) ::apollo::task_manager::CycleRoutingTask();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::task_manager::CycleRoutingTask::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_CycleRoutingTask =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsCycleRoutingTask}, {
      &protobuf_modules_2fcommon_5fmsgs_2fexternal_5fcommand_5fmsgs_2flane_5ffollow_5fcommand_2eproto::scc_info_LaneFollowCommand.base,}};

static void InitDefaultsParkingRoutingTask() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::task_manager::_ParkingRoutingTask_default_instance_;
    new (ptr) ::apollo::task_manager::ParkingRoutingTask();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::task_manager::ParkingRoutingTask::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ParkingRoutingTask =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsParkingRoutingTask}, {
      &protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto::scc_info_RoutingRequest.base,}};

static void InitDefaultsParkGoRoutingTask() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::task_manager::_ParkGoRoutingTask_default_instance_;
    new (ptr) ::apollo::task_manager::ParkGoRoutingTask();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::task_manager::ParkGoRoutingTask::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ParkGoRoutingTask =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsParkGoRoutingTask}, {
      &protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto::scc_info_RoutingRequest.base,}};

static void InitDefaultsTask() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::task_manager::_Task_default_instance_;
    new (ptr) ::apollo::task_manager::Task();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::task_manager::Task::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<4> scc_info_Task =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 4, InitDefaultsTask}, {
      &protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fheader_2eproto::scc_info_Header.base,
      &protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_CycleRoutingTask.base,
      &protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_ParkingRoutingTask.base,
      &protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_ParkGoRoutingTask.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CycleRoutingTask.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ParkingRoutingTask.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ParkGoRoutingTask.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Task.base);
}

::google::protobuf::Metadata file_level_metadata[4];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::CycleRoutingTask, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::CycleRoutingTask, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::CycleRoutingTask, cycle_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::CycleRoutingTask, lane_follow_command_),
  1,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::ParkingRoutingTask, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::ParkingRoutingTask, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::ParkingRoutingTask, lane_width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::ParkingRoutingTask, routing_request_),
  1,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::ParkGoRoutingTask, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::ParkGoRoutingTask, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::ParkGoRoutingTask, park_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::ParkGoRoutingTask, routing_request_),
  1,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::Task, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::Task, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::Task, header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::Task, task_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::Task, task_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::Task, cycle_routing_task_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::Task, parking_routing_task_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::task_manager::Task, park_go_routing_task_),
  1,
  0,
  5,
  2,
  3,
  4,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::apollo::task_manager::CycleRoutingTask)},
  { 9, 16, sizeof(::apollo::task_manager::ParkingRoutingTask)},
  { 18, 25, sizeof(::apollo::task_manager::ParkGoRoutingTask)},
  { 27, 38, sizeof(::apollo::task_manager::Task)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::task_manager::_CycleRoutingTask_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::task_manager::_ParkingRoutingTask_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::task_manager::_ParkGoRoutingTask_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::task_manager::_Task_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "modules/common_msgs/task_manager_msgs/task_manager.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n8modules/common_msgs/task_manager_msgs/"
      "task_manager.proto\022\023apollo.task_manager\032"
      "+modules/common_msgs/basic_msgs/header.p"
      "roto\032.modules/common_msgs/routing_msgs/r"
      "outing.proto\032Cmodules/common_msgs/extern"
      "al_command_msgs/lane_follow_command.prot"
      "o\"n\n\020CycleRoutingTask\022\021\n\tcycle_num\030\001 \001(\005"
      "\022G\n\023lane_follow_command\030\002 \001(\0132*.apollo.e"
      "xternal_command.LaneFollowCommand\"a\n\022Par"
      "kingRoutingTask\022\022\n\nlane_width\030\001 \001(\001\0227\n\017r"
      "outing_request\030\002 \001(\0132\036.apollo.routing.Ro"
      "utingRequest\"_\n\021ParkGoRoutingTask\022\021\n\tpar"
      "k_time\030\001 \001(\005\0227\n\017routing_request\030\002 \001(\0132\036."
      "apollo.routing.RoutingRequest\"\302\002\n\004Task\022%"
      "\n\006header\030\001 \001(\0132\025.apollo.common.Header\022\021\n"
      "\ttask_name\030\002 \001(\t\0220\n\ttask_type\030\003 \001(\0162\035.ap"
      "ollo.task_manager.TaskType\022A\n\022cycle_rout"
      "ing_task\030\004 \001(\0132%.apollo.task_manager.Cyc"
      "leRoutingTask\022E\n\024parking_routing_task\030\005 "
      "\001(\0132\'.apollo.task_manager.ParkingRouting"
      "Task\022D\n\024park_go_routing_task\030\006 \001(\0132&.apo"
      "llo.task_manager.ParkGoRoutingTask*G\n\010Ta"
      "skType\022\021\n\rCYCLE_ROUTING\020\000\022\023\n\017PARKING_ROU"
      "TING\020\001\022\023\n\017PARK_GO_ROUTING\020\002*V\n\014JunctionT"
      "ype\022\013\n\007UNKNOWN\020\000\022\013\n\007IN_ROAD\020\001\022\016\n\nCROSS_R"
      "OAD\020\002\022\r\n\tFORK_ROAD\020\003\022\r\n\tMAIN_SIDE\020\004"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1035);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "modules/common_msgs/task_manager_msgs/task_manager.proto", &protobuf_RegisterTypes);
  ::protobuf_modules_2fcommon_5fmsgs_2fbasic_5fmsgs_2fheader_2eproto::AddDescriptors();
  ::protobuf_modules_2fcommon_5fmsgs_2frouting_5fmsgs_2frouting_2eproto::AddDescriptors();
  ::protobuf_modules_2fcommon_5fmsgs_2fexternal_5fcommand_5fmsgs_2flane_5ffollow_5fcommand_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto
namespace apollo {
namespace task_manager {
const ::google::protobuf::EnumDescriptor* TaskType_descriptor() {
  protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::file_level_enum_descriptors[0];
}
bool TaskType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* JunctionType_descriptor() {
  protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::file_level_enum_descriptors[1];
}
bool JunctionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void CycleRoutingTask::InitAsDefaultInstance() {
  ::apollo::task_manager::_CycleRoutingTask_default_instance_._instance.get_mutable()->lane_follow_command_ = const_cast< ::apollo::external_command::LaneFollowCommand*>(
      ::apollo::external_command::LaneFollowCommand::internal_default_instance());
}
void CycleRoutingTask::clear_lane_follow_command() {
  if (lane_follow_command_ != NULL) lane_follow_command_->Clear();
  clear_has_lane_follow_command();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CycleRoutingTask::kCycleNumFieldNumber;
const int CycleRoutingTask::kLaneFollowCommandFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CycleRoutingTask::CycleRoutingTask()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_CycleRoutingTask.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.task_manager.CycleRoutingTask)
}
CycleRoutingTask::CycleRoutingTask(const CycleRoutingTask& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_lane_follow_command()) {
    lane_follow_command_ = new ::apollo::external_command::LaneFollowCommand(*from.lane_follow_command_);
  } else {
    lane_follow_command_ = NULL;
  }
  cycle_num_ = from.cycle_num_;
  // @@protoc_insertion_point(copy_constructor:apollo.task_manager.CycleRoutingTask)
}

void CycleRoutingTask::SharedCtor() {
  ::memset(&lane_follow_command_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cycle_num_) -
      reinterpret_cast<char*>(&lane_follow_command_)) + sizeof(cycle_num_));
}

CycleRoutingTask::~CycleRoutingTask() {
  // @@protoc_insertion_point(destructor:apollo.task_manager.CycleRoutingTask)
  SharedDtor();
}

void CycleRoutingTask::SharedDtor() {
  if (this != internal_default_instance()) delete lane_follow_command_;
}

void CycleRoutingTask::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CycleRoutingTask::descriptor() {
  ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CycleRoutingTask& CycleRoutingTask::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_CycleRoutingTask.base);
  return *internal_default_instance();
}


void CycleRoutingTask::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.task_manager.CycleRoutingTask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(lane_follow_command_ != NULL);
    lane_follow_command_->Clear();
  }
  cycle_num_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CycleRoutingTask::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.task_manager.CycleRoutingTask)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 cycle_num = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_cycle_num();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cycle_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.external_command.LaneFollowCommand lane_follow_command = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_lane_follow_command()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.task_manager.CycleRoutingTask)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.task_manager.CycleRoutingTask)
  return false;
#undef DO_
}

void CycleRoutingTask::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.task_manager.CycleRoutingTask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 cycle_num = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->cycle_num(), output);
  }

  // optional .apollo.external_command.LaneFollowCommand lane_follow_command = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_lane_follow_command(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.task_manager.CycleRoutingTask)
}

::google::protobuf::uint8* CycleRoutingTask::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.task_manager.CycleRoutingTask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 cycle_num = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->cycle_num(), target);
  }

  // optional .apollo.external_command.LaneFollowCommand lane_follow_command = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_lane_follow_command(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.task_manager.CycleRoutingTask)
  return target;
}

size_t CycleRoutingTask::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.task_manager.CycleRoutingTask)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional .apollo.external_command.LaneFollowCommand lane_follow_command = 2;
    if (has_lane_follow_command()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *lane_follow_command_);
    }

    // optional int32 cycle_num = 1;
    if (has_cycle_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cycle_num());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CycleRoutingTask::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.task_manager.CycleRoutingTask)
  GOOGLE_DCHECK_NE(&from, this);
  const CycleRoutingTask* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CycleRoutingTask>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.task_manager.CycleRoutingTask)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.task_manager.CycleRoutingTask)
    MergeFrom(*source);
  }
}

void CycleRoutingTask::MergeFrom(const CycleRoutingTask& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.task_manager.CycleRoutingTask)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_lane_follow_command()->::apollo::external_command::LaneFollowCommand::MergeFrom(from.lane_follow_command());
    }
    if (cached_has_bits & 0x00000002u) {
      cycle_num_ = from.cycle_num_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void CycleRoutingTask::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.task_manager.CycleRoutingTask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CycleRoutingTask::CopyFrom(const CycleRoutingTask& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.task_manager.CycleRoutingTask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CycleRoutingTask::IsInitialized() const {
  if (has_lane_follow_command()) {
    if (!this->lane_follow_command_->IsInitialized()) return false;
  }
  return true;
}

void CycleRoutingTask::Swap(CycleRoutingTask* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CycleRoutingTask::InternalSwap(CycleRoutingTask* other) {
  using std::swap;
  swap(lane_follow_command_, other->lane_follow_command_);
  swap(cycle_num_, other->cycle_num_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CycleRoutingTask::GetMetadata() const {
  protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ParkingRoutingTask::InitAsDefaultInstance() {
  ::apollo::task_manager::_ParkingRoutingTask_default_instance_._instance.get_mutable()->routing_request_ = const_cast< ::apollo::routing::RoutingRequest*>(
      ::apollo::routing::RoutingRequest::internal_default_instance());
}
void ParkingRoutingTask::clear_routing_request() {
  if (routing_request_ != NULL) routing_request_->Clear();
  clear_has_routing_request();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParkingRoutingTask::kLaneWidthFieldNumber;
const int ParkingRoutingTask::kRoutingRequestFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParkingRoutingTask::ParkingRoutingTask()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_ParkingRoutingTask.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.task_manager.ParkingRoutingTask)
}
ParkingRoutingTask::ParkingRoutingTask(const ParkingRoutingTask& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_routing_request()) {
    routing_request_ = new ::apollo::routing::RoutingRequest(*from.routing_request_);
  } else {
    routing_request_ = NULL;
  }
  lane_width_ = from.lane_width_;
  // @@protoc_insertion_point(copy_constructor:apollo.task_manager.ParkingRoutingTask)
}

void ParkingRoutingTask::SharedCtor() {
  ::memset(&routing_request_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lane_width_) -
      reinterpret_cast<char*>(&routing_request_)) + sizeof(lane_width_));
}

ParkingRoutingTask::~ParkingRoutingTask() {
  // @@protoc_insertion_point(destructor:apollo.task_manager.ParkingRoutingTask)
  SharedDtor();
}

void ParkingRoutingTask::SharedDtor() {
  if (this != internal_default_instance()) delete routing_request_;
}

void ParkingRoutingTask::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ParkingRoutingTask::descriptor() {
  ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ParkingRoutingTask& ParkingRoutingTask::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_ParkingRoutingTask.base);
  return *internal_default_instance();
}


void ParkingRoutingTask::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.task_manager.ParkingRoutingTask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(routing_request_ != NULL);
    routing_request_->Clear();
  }
  lane_width_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ParkingRoutingTask::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.task_manager.ParkingRoutingTask)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double lane_width = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_lane_width();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lane_width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.routing.RoutingRequest routing_request = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_routing_request()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.task_manager.ParkingRoutingTask)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.task_manager.ParkingRoutingTask)
  return false;
#undef DO_
}

void ParkingRoutingTask::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.task_manager.ParkingRoutingTask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double lane_width = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->lane_width(), output);
  }

  // optional .apollo.routing.RoutingRequest routing_request = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_routing_request(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.task_manager.ParkingRoutingTask)
}

::google::protobuf::uint8* ParkingRoutingTask::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.task_manager.ParkingRoutingTask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double lane_width = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->lane_width(), target);
  }

  // optional .apollo.routing.RoutingRequest routing_request = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_routing_request(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.task_manager.ParkingRoutingTask)
  return target;
}

size_t ParkingRoutingTask::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.task_manager.ParkingRoutingTask)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional .apollo.routing.RoutingRequest routing_request = 2;
    if (has_routing_request()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *routing_request_);
    }

    // optional double lane_width = 1;
    if (has_lane_width()) {
      total_size += 1 + 8;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ParkingRoutingTask::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.task_manager.ParkingRoutingTask)
  GOOGLE_DCHECK_NE(&from, this);
  const ParkingRoutingTask* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ParkingRoutingTask>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.task_manager.ParkingRoutingTask)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.task_manager.ParkingRoutingTask)
    MergeFrom(*source);
  }
}

void ParkingRoutingTask::MergeFrom(const ParkingRoutingTask& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.task_manager.ParkingRoutingTask)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_routing_request()->::apollo::routing::RoutingRequest::MergeFrom(from.routing_request());
    }
    if (cached_has_bits & 0x00000002u) {
      lane_width_ = from.lane_width_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ParkingRoutingTask::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.task_manager.ParkingRoutingTask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParkingRoutingTask::CopyFrom(const ParkingRoutingTask& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.task_manager.ParkingRoutingTask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParkingRoutingTask::IsInitialized() const {
  return true;
}

void ParkingRoutingTask::Swap(ParkingRoutingTask* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParkingRoutingTask::InternalSwap(ParkingRoutingTask* other) {
  using std::swap;
  swap(routing_request_, other->routing_request_);
  swap(lane_width_, other->lane_width_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ParkingRoutingTask::GetMetadata() const {
  protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ParkGoRoutingTask::InitAsDefaultInstance() {
  ::apollo::task_manager::_ParkGoRoutingTask_default_instance_._instance.get_mutable()->routing_request_ = const_cast< ::apollo::routing::RoutingRequest*>(
      ::apollo::routing::RoutingRequest::internal_default_instance());
}
void ParkGoRoutingTask::clear_routing_request() {
  if (routing_request_ != NULL) routing_request_->Clear();
  clear_has_routing_request();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ParkGoRoutingTask::kParkTimeFieldNumber;
const int ParkGoRoutingTask::kRoutingRequestFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ParkGoRoutingTask::ParkGoRoutingTask()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_ParkGoRoutingTask.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.task_manager.ParkGoRoutingTask)
}
ParkGoRoutingTask::ParkGoRoutingTask(const ParkGoRoutingTask& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_routing_request()) {
    routing_request_ = new ::apollo::routing::RoutingRequest(*from.routing_request_);
  } else {
    routing_request_ = NULL;
  }
  park_time_ = from.park_time_;
  // @@protoc_insertion_point(copy_constructor:apollo.task_manager.ParkGoRoutingTask)
}

void ParkGoRoutingTask::SharedCtor() {
  ::memset(&routing_request_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&park_time_) -
      reinterpret_cast<char*>(&routing_request_)) + sizeof(park_time_));
}

ParkGoRoutingTask::~ParkGoRoutingTask() {
  // @@protoc_insertion_point(destructor:apollo.task_manager.ParkGoRoutingTask)
  SharedDtor();
}

void ParkGoRoutingTask::SharedDtor() {
  if (this != internal_default_instance()) delete routing_request_;
}

void ParkGoRoutingTask::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ParkGoRoutingTask::descriptor() {
  ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ParkGoRoutingTask& ParkGoRoutingTask::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_ParkGoRoutingTask.base);
  return *internal_default_instance();
}


void ParkGoRoutingTask::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.task_manager.ParkGoRoutingTask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(routing_request_ != NULL);
    routing_request_->Clear();
  }
  park_time_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ParkGoRoutingTask::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.task_manager.ParkGoRoutingTask)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 park_time = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_park_time();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &park_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.routing.RoutingRequest routing_request = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_routing_request()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.task_manager.ParkGoRoutingTask)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.task_manager.ParkGoRoutingTask)
  return false;
#undef DO_
}

void ParkGoRoutingTask::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.task_manager.ParkGoRoutingTask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 park_time = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->park_time(), output);
  }

  // optional .apollo.routing.RoutingRequest routing_request = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_routing_request(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.task_manager.ParkGoRoutingTask)
}

::google::protobuf::uint8* ParkGoRoutingTask::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.task_manager.ParkGoRoutingTask)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 park_time = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->park_time(), target);
  }

  // optional .apollo.routing.RoutingRequest routing_request = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_routing_request(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.task_manager.ParkGoRoutingTask)
  return target;
}

size_t ParkGoRoutingTask::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.task_manager.ParkGoRoutingTask)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional .apollo.routing.RoutingRequest routing_request = 2;
    if (has_routing_request()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *routing_request_);
    }

    // optional int32 park_time = 1;
    if (has_park_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->park_time());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ParkGoRoutingTask::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.task_manager.ParkGoRoutingTask)
  GOOGLE_DCHECK_NE(&from, this);
  const ParkGoRoutingTask* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ParkGoRoutingTask>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.task_manager.ParkGoRoutingTask)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.task_manager.ParkGoRoutingTask)
    MergeFrom(*source);
  }
}

void ParkGoRoutingTask::MergeFrom(const ParkGoRoutingTask& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.task_manager.ParkGoRoutingTask)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_routing_request()->::apollo::routing::RoutingRequest::MergeFrom(from.routing_request());
    }
    if (cached_has_bits & 0x00000002u) {
      park_time_ = from.park_time_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ParkGoRoutingTask::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.task_manager.ParkGoRoutingTask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ParkGoRoutingTask::CopyFrom(const ParkGoRoutingTask& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.task_manager.ParkGoRoutingTask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ParkGoRoutingTask::IsInitialized() const {
  return true;
}

void ParkGoRoutingTask::Swap(ParkGoRoutingTask* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ParkGoRoutingTask::InternalSwap(ParkGoRoutingTask* other) {
  using std::swap;
  swap(routing_request_, other->routing_request_);
  swap(park_time_, other->park_time_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ParkGoRoutingTask::GetMetadata() const {
  protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Task::InitAsDefaultInstance() {
  ::apollo::task_manager::_Task_default_instance_._instance.get_mutable()->header_ = const_cast< ::apollo::common::Header*>(
      ::apollo::common::Header::internal_default_instance());
  ::apollo::task_manager::_Task_default_instance_._instance.get_mutable()->cycle_routing_task_ = const_cast< ::apollo::task_manager::CycleRoutingTask*>(
      ::apollo::task_manager::CycleRoutingTask::internal_default_instance());
  ::apollo::task_manager::_Task_default_instance_._instance.get_mutable()->parking_routing_task_ = const_cast< ::apollo::task_manager::ParkingRoutingTask*>(
      ::apollo::task_manager::ParkingRoutingTask::internal_default_instance());
  ::apollo::task_manager::_Task_default_instance_._instance.get_mutable()->park_go_routing_task_ = const_cast< ::apollo::task_manager::ParkGoRoutingTask*>(
      ::apollo::task_manager::ParkGoRoutingTask::internal_default_instance());
}
void Task::clear_header() {
  if (header_ != NULL) header_->Clear();
  clear_has_header();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Task::kHeaderFieldNumber;
const int Task::kTaskNameFieldNumber;
const int Task::kTaskTypeFieldNumber;
const int Task::kCycleRoutingTaskFieldNumber;
const int Task::kParkingRoutingTaskFieldNumber;
const int Task::kParkGoRoutingTaskFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Task::Task()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_Task.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.task_manager.Task)
}
Task::Task(const Task& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  task_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_task_name()) {
    task_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.task_name_);
  }
  if (from.has_header()) {
    header_ = new ::apollo::common::Header(*from.header_);
  } else {
    header_ = NULL;
  }
  if (from.has_cycle_routing_task()) {
    cycle_routing_task_ = new ::apollo::task_manager::CycleRoutingTask(*from.cycle_routing_task_);
  } else {
    cycle_routing_task_ = NULL;
  }
  if (from.has_parking_routing_task()) {
    parking_routing_task_ = new ::apollo::task_manager::ParkingRoutingTask(*from.parking_routing_task_);
  } else {
    parking_routing_task_ = NULL;
  }
  if (from.has_park_go_routing_task()) {
    park_go_routing_task_ = new ::apollo::task_manager::ParkGoRoutingTask(*from.park_go_routing_task_);
  } else {
    park_go_routing_task_ = NULL;
  }
  task_type_ = from.task_type_;
  // @@protoc_insertion_point(copy_constructor:apollo.task_manager.Task)
}

void Task::SharedCtor() {
  task_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&task_type_) -
      reinterpret_cast<char*>(&header_)) + sizeof(task_type_));
}

Task::~Task() {
  // @@protoc_insertion_point(destructor:apollo.task_manager.Task)
  SharedDtor();
}

void Task::SharedDtor() {
  task_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete header_;
  if (this != internal_default_instance()) delete cycle_routing_task_;
  if (this != internal_default_instance()) delete parking_routing_task_;
  if (this != internal_default_instance()) delete park_go_routing_task_;
}

void Task::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Task::descriptor() {
  ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Task& Task::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::scc_info_Task.base);
  return *internal_default_instance();
}


void Task::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.task_manager.Task)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 31u) {
    if (cached_has_bits & 0x00000001u) {
      task_name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(header_ != NULL);
      header_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(cycle_routing_task_ != NULL);
      cycle_routing_task_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(parking_routing_task_ != NULL);
      parking_routing_task_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(park_go_routing_task_ != NULL);
      park_go_routing_task_->Clear();
    }
  }
  task_type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Task::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.task_manager.Task)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .apollo.common.Header header = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string task_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_task_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->task_name().data(), static_cast<int>(this->task_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "apollo.task_manager.Task.task_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.task_manager.TaskType task_type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::apollo::task_manager::TaskType_IsValid(value)) {
            set_task_type(static_cast< ::apollo::task_manager::TaskType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                3, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.task_manager.CycleRoutingTask cycle_routing_task = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_cycle_routing_task()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.task_manager.ParkingRoutingTask parking_routing_task = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_parking_routing_task()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.task_manager.ParkGoRoutingTask park_go_routing_task = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_park_go_routing_task()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.task_manager.Task)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.task_manager.Task)
  return false;
#undef DO_
}

void Task::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.task_manager.Task)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .apollo.common.Header header = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_header(), output);
  }

  // optional string task_name = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->task_name().data(), static_cast<int>(this->task_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.task_manager.Task.task_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->task_name(), output);
  }

  // optional .apollo.task_manager.TaskType task_type = 3;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->task_type(), output);
  }

  // optional .apollo.task_manager.CycleRoutingTask cycle_routing_task = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_cycle_routing_task(), output);
  }

  // optional .apollo.task_manager.ParkingRoutingTask parking_routing_task = 5;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_parking_routing_task(), output);
  }

  // optional .apollo.task_manager.ParkGoRoutingTask park_go_routing_task = 6;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->_internal_park_go_routing_task(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.task_manager.Task)
}

::google::protobuf::uint8* Task::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.task_manager.Task)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .apollo.common.Header header = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_header(), deterministic, target);
  }

  // optional string task_name = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->task_name().data(), static_cast<int>(this->task_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "apollo.task_manager.Task.task_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->task_name(), target);
  }

  // optional .apollo.task_manager.TaskType task_type = 3;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->task_type(), target);
  }

  // optional .apollo.task_manager.CycleRoutingTask cycle_routing_task = 4;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_cycle_routing_task(), deterministic, target);
  }

  // optional .apollo.task_manager.ParkingRoutingTask parking_routing_task = 5;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_parking_routing_task(), deterministic, target);
  }

  // optional .apollo.task_manager.ParkGoRoutingTask park_go_routing_task = 6;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->_internal_park_go_routing_task(), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.task_manager.Task)
  return target;
}

size_t Task::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.task_manager.Task)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 63u) {
    // optional string task_name = 2;
    if (has_task_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->task_name());
    }

    // optional .apollo.common.Header header = 1;
    if (has_header()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *header_);
    }

    // optional .apollo.task_manager.CycleRoutingTask cycle_routing_task = 4;
    if (has_cycle_routing_task()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *cycle_routing_task_);
    }

    // optional .apollo.task_manager.ParkingRoutingTask parking_routing_task = 5;
    if (has_parking_routing_task()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *parking_routing_task_);
    }

    // optional .apollo.task_manager.ParkGoRoutingTask park_go_routing_task = 6;
    if (has_park_go_routing_task()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *park_go_routing_task_);
    }

    // optional .apollo.task_manager.TaskType task_type = 3;
    if (has_task_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->task_type());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Task::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.task_manager.Task)
  GOOGLE_DCHECK_NE(&from, this);
  const Task* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Task>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.task_manager.Task)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.task_manager.Task)
    MergeFrom(*source);
  }
}

void Task::MergeFrom(const Task& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.task_manager.Task)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_task_name();
      task_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.task_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_header()->::apollo::common::Header::MergeFrom(from.header());
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_cycle_routing_task()->::apollo::task_manager::CycleRoutingTask::MergeFrom(from.cycle_routing_task());
    }
    if (cached_has_bits & 0x00000008u) {
      mutable_parking_routing_task()->::apollo::task_manager::ParkingRoutingTask::MergeFrom(from.parking_routing_task());
    }
    if (cached_has_bits & 0x00000010u) {
      mutable_park_go_routing_task()->::apollo::task_manager::ParkGoRoutingTask::MergeFrom(from.park_go_routing_task());
    }
    if (cached_has_bits & 0x00000020u) {
      task_type_ = from.task_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Task::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.task_manager.Task)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Task::CopyFrom(const Task& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.task_manager.Task)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Task::IsInitialized() const {
  if (has_cycle_routing_task()) {
    if (!this->cycle_routing_task_->IsInitialized()) return false;
  }
  return true;
}

void Task::Swap(Task* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Task::InternalSwap(Task* other) {
  using std::swap;
  task_name_.Swap(&other->task_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(header_, other->header_);
  swap(cycle_routing_task_, other->cycle_routing_task_);
  swap(parking_routing_task_, other->parking_routing_task_);
  swap(park_go_routing_task_, other->park_go_routing_task_);
  swap(task_type_, other->task_type_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Task::GetMetadata() const {
  protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_modules_2fcommon_5fmsgs_2ftask_5fmanager_5fmsgs_2ftask_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace task_manager
}  // namespace apollo
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::task_manager::CycleRoutingTask* Arena::CreateMaybeMessage< ::apollo::task_manager::CycleRoutingTask >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::task_manager::CycleRoutingTask >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::task_manager::ParkingRoutingTask* Arena::CreateMaybeMessage< ::apollo::task_manager::ParkingRoutingTask >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::task_manager::ParkingRoutingTask >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::task_manager::ParkGoRoutingTask* Arena::CreateMaybeMessage< ::apollo::task_manager::ParkGoRoutingTask >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::task_manager::ParkGoRoutingTask >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::task_manager::Task* Arena::CreateMaybeMessage< ::apollo::task_manager::Task >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::task_manager::Task >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
