
# 地图保存路径 ==> 根目录
# map_save_path: /workspaces/CodexOpenExtraData/data/2026-04-21/16102220208346880_1420_000_1440_000-O/map_data
map_save_path: /workspaces/CodexOpenExtraData/data/2026-01-28/2026-01-28-09-31-37-O/map_data
# map_save_path: /workspaces/CodexOpenExtraData/data/2026-04-16/2026-04-16-17-13-20-O/map_data
# map_save_path: /workspaces/CodexOpenExtraData/data/1970-01-12/1970-01-12-07-25-18-O/map_data

init:
  # 先验地图：false ; 构建地图：true
  # 如果使用了地图定位得到的 pose，那么 设置为 false;
  # 如果是边建图边定位，那么设置为 true;
  b_use_pose_center: false