
float64 local_time	# in ms
float64 UTC_time	# in ms
int32   message_num		

self_state/InsStatus   ins_status
sensor/PosType         pos_type       

float64 gaussX		# in  m
float64 gaussY		# in  m
float64 height		# in  m
float64 vNorth		# in  m/s
float64 vEast		# in  m/s
float64 vUp		# in  m/s
float64 roll		# in  degrees
float64 pitch		# in  degrees
float64 azimuth	# in  degrees

float64 dev_gaussX	# in  m
float64 dev_gaussY	# in  m
float64 dev_height	# in  m
float64 dev_vNorth	# in  m/s
float64 dev_vEast	# in  m/s
float64 dev_vUp	# in  m/s
float64 dev_roll	# in  degrees
float64 dev_pitch	# in  degrees
float64 dev_azimuth	# in  degrees

float64 latitude	# in  degrees	
float64 longitude	# in  degrees

float64[4] reserved


