[general]
b_do_undistort = 1
; 0 1 2  => 左转90  不转  右转90
b_lt_none_rt = 1

dist_threshold = 100

[calibration]
calib_file_path = /workspaces/CodexOpen/install/bin/data/PerceptionFuse/calib/ar0231_front.ini
; calib_file_path = /workspaces/CodexOpen/install/bin/data/PerceptionFuse/calib/ar0231_left_front.ini
; calib_file_path = /workspaces/CodexOpen/install/bin/data/PerceptionFuse/calib/ar0231_right_front.ini
; calib_file_path = /workspaces/CodexOpen/install/bin/data/PerceptionFuse/calib/ar0231_front_left.ini
; calib_file_path = /workspaces/CodexOpen/install/bin/data/PerceptionFuse/calib/ar0231_front_right.ini
; calib_file_path = /workspaces/CodexOpen/install/bin/data/PerceptionFuse/calib/p12_front.ini
; calib_file_path = /workspaces/CodexOpen/install/bin/data/PerceptionFuse/calib/p12_left_front.ini
; calib_file_path = /workspaces/CodexOpen/install/bin/data/PerceptionFuse/calib/p12_right_front.ini
; calib_file_path = /workspaces/CodexOpen/install/bin/data/PerceptionFuse/calib/imx390_front.ini
