[general]
b_compressed = 1

rate = 10

[topics]
image_topic = /sensor/image/ar0231_front/compressed
; image_topic = /image/test_image/compressed
lidar_topic = /rslidar_points
; lidar_topic = /velodyne_points
